### ISSUE TITLE
'Value does not fall within the expected range' Exceptions

### ISSUE THREAD

**Issue by RickStrahl** [MicrosoftEdge/WebView2Feedback#1552]
I'm looking through my operational logs from customer exceptions and I'm seeing a ton of errors coming in from this particular failure:

```text
exbasemsg
Value does not fall within the expected range.

exsource
Microsoft.Web.WebView2.Core

extrace
at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller.MoveFocus(COREWEBVIEW2_MOVE_FOCUS_REASON reason)
   at Microsoft.Web.WebView2.Core.CoreWebView2Controller.MoveFocus(CoreWebView2MoveFocusReason reason)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.KeyboardDevice.ChangeFocus(DependencyObject focus, Int32 timestamp)
   at System.Windows.Input.KeyboardDevice.TryChangeFocus(DependencyObject newFocus, IKeyboardInputProvider keyboardInputProvider, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
   at System.Windows.Input.KeyboardDevice.Focus(DependencyObject focus, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
   at System.Windows.Input.KeyboardDevice.Focus(IInputElement element)
   at System.Windows.Interop.HwndKeyboardInputProvider.OnSetFocus(IntPtr hwnd)
   at System.Windows.Interop.HwndKeyboardInputProvider.FilterMessage(IntPtr hwnd, WindowMessage message, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

This is all internal to the WebView2 control apparently as there's no application code in the stack trace. 

I know sufficiently vague especially since I can't provide a repro scenario, but seeing a lot of these popping up I thought to bring it up here. It looks like it has to do with focus switches between the control and the host application.

This is for:

* WebView2 Control
* In WPF application
* Latest Release Runtime 91.0.864.71
* WebView .NET Control 1.0.864.35

[AB#34766572](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/34766572)

**Comment by champnic** [comment]
Thanks for the bug report @RickStrahl! That error message seems like it maps to `E_INVALIDARG` but looking at the code I'm not yet sure how it would happen. Are the SDK and Runtime versions you provided from the machines that are hitting this?

**Comment by fvanheeswijk** [comment]
```
System.ArgumentException: Value does not fall within the expected range.
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller.MoveFocus(COREWEBVIEW2_MOVE_FOCUS_REASON reason)
   at Microsoft.Web.WebView2.Core.CoreWebView2Controller.MoveFocus(CoreWebView2MoveFocusReason reason)
   at Microsoft.Web.WebView2.WinForms.WebView2.OnGotFocus(EventArgs e)
   at System.Windows.Forms.Control.InvokeGotFocus(Control toInvoke, EventArgs e)
   at System.Windows.Forms.Control.WmSetFocus(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at Microsoft.Web.WebView2.WinForms.WebView2.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

We're getting a similar error, maybe this stack trace is of help.

It doesn't seem to be triggered via our application code either, though we're unsure what `System.Windows.Forms.NativeWindow.DebuggableCallback` exactly is.

**Comment by RickStrahl** [comment]
@champnic The control version is what I mention since these are all very recent and had to be installed in the last week or so. Runtime too since the runtime installs with product install, but it is possible a different runtime is used (could be Canary builds).

 Currently I don't log WebView runtime versions and frankly I don't want to :smile:

**Comment by cuiliang** [comment]
I am getting similar error, maybe this stacktrace is of help.
```
ArgumentException
   在 Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller.MoveFocus(COREWEBVIEW2_MOVE_FOCUS_REASON reason)
   在 Microsoft.Web.WebView2.Core.CoreWebView2Controller.MoveFocus(CoreWebView2MoveFocusReason reason)
   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   在 System.Windows.Input.InputManager.ProcessStagingArea()
   在 System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   在 System.Windows.Input.KeyboardDevice.ChangeFocus(DependencyObject focus, Int32 timestamp)
   在 System.Windows.Input.KeyboardDevice.TryChangeFocus(DependencyObject newFocus, IKeyboardInputProvider keyboardInputProvider, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
   在 System.Windows.Input.KeyboardDevice.Focus(DependencyObject focus, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
   在 System.Windows.Input.KeyboardDevice.Focus(IInputElement element)
   在 System.Windows.UIElement.Focus()
   在 System.Windows.FrameworkElement.OnPreviewGotKeyboardFocus(Object sender, KeyboardFocusChangedEventArgs e)
   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   在 System.Windows.Input.InputManager.ProcessStagingArea()
   在 System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   在 System.Windows.Input.KeyboardDevice.TryChangeFocus(DependencyObject newFocus, IKeyboardInputProvider keyboardInputProvider, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
   在 System.Windows.Input.KeyboardDevice.Focus(DependencyObject focus, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
   在 System.Windows.Input.KeyboardDevice.Focus(IInputElement element)
   在 System.Windows.Interop.HwndKeyboardInputProvider.OnSetFocus(IntPtr hwnd)
   在 System.Windows.Interop.HwndKeyboardInputProvider.FilterMessage(IntPtr hwnd, WindowMessage message, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by fvanheeswijk** [comment]
We are still getting the same error as reported on 22 July, we had to disable WebView2 for our production application because this is not an acceptable experience for our users.
When will it be fixed?

**Comment by champnic** [comment]
For anyone running into this, do you have any repro steps that could help here? Or does this just randomly happen?

Are you all listening to the ProcessFailed event? My guess is that this is a browser process crash of some sort, which then manifests as this exception when focus attempts to move to the WebView2. Unfortunately it's hard to do anything with just these stacks without a dump, repro steps, or an app that can repro this issue.

**Comment by fvanheeswijk** [comment]
For our users it is happening randomly, we may see a relation with running the client on terminal servers but we are still unsure about that, it could also just be coincidence.

We are not listening to the ProcessFailed event yet, we could surely log some of the data that it shows (except frame data I suppose due to confidentiality), but we're unsure how helpful that will be.

Is there no way to see what is going wrong exactly? It looks like Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller.MoveFocus(COREWEBVIEW2_MOVE_FOCUS_REASON reason) is receiving an invalid argument? Of what process would you need a dump when this occurs?

**Comment by RickStrahl** [comment]
@champnic I'd love to give you a bug report, but like @fvanheeswijk I have not been able to reproduce this reliably. I just see the errors in my customer analytics that capture exceptions and occasionally in my error logs as well. The error is rare, but I have to 5 to 10 of those in my logs a day.

The problem as you say is that the error trace is not coming from my app but from deep in the Edge Control's code, so there's nothing that I can track. I have no idea what triggered it, and when I see the errors they seem to be one-offs - ie. it's not happening on the same machine each time. 

I capture the Edge Process shutdown event, but that thing is pretty useless other than letting me know that we're done :smile: - there's no further error information there that could help. 

I log both and I don't see them both in combination show up. The former crashes the app with a hard exception with no recycling from that.

**Comment by champnic** [comment]
@fvanheeswijk The reason I asked about the event is that it's likely a crash in the browser processes is making the CoreWebView2 and other underlying objects invalid. MoveFocus just happens to be the first thing in the WebView2 control that runs into that. We generally recommend listening to the ProcessFailed event and recreating the WebView2 when some crashes happen.

@RickStrahl Ya, as you mention the ProcessFailed event is not much help besides knowing you need to recreate the WebView2.

**Comment by BrianRoach** [comment]
> For anyone running into this, do you have any repro steps that could help here? Or does this just randomly happen?
> 
> Are you all listening to the ProcessFailed event? My guess is that this is a browser process crash of some sort, which then manifests as this exception when focus attempts to move to the WebView2. Unfortunately it's hard to do anything with just these stacks without a dump, repro steps, or an app that can repro this issue.

Seeing this as well, but it is very random.  Happened to one user when she attempted to take a screen shot of the application (with a webview exposed)

**Comment by RickStrahl** [comment]
@champnic - an update here for my particular application, which is a WPF application. The specific error I referenced in the original post appears to be related to Window activation of the host application, and focus transfer from the top level application into the WebView.

In the app what happens is that when the Window is deactivated, and then focus returns later, my App OnActivate checks to see if the browser was previously active and explicitly sets the focus back to it - because it won't automatically go back there on its own. I now think that that code is what triggered the problem,

After a lot of trial and error experimentation I seem to have resolved this issue by forcing the code through an async Dispatcher rather than running the `async void` method:

**old code**

```cs
protected async void OnActivated(object sender, EventArgs e)
{
        // Active Menu Item deactivation don't refocus
        if (MainMenu.Items.OfType<MenuItem>().Any(item => item.IsHighlighted))
            return;

        if (_saveIsEditorFocused && Model.ActiveEditor != null)
        {
            try
            {
                await Model.ActiveEditor.SetEditorFocus();  // WebView Interop
                await Model.ActiveEditor.RestyleEditor();
            }
            catch
            {
                // ignore interop errors
            }
        }
}
```

** new code**

```csharp
protected void OnActivated(object sender, EventArgs e)
{
    Dispatcher.InvokeAsync(async () =>
    {
        // Active Menu Item deactivation don't refocus
        if (MainMenu.Items.OfType<MenuItem>().Any(item => item.IsHighlighted))
            return;

        if (_saveIsEditorFocused && Model.ActiveEditor != null)
        {
            try
            {
                await Model.ActiveEditor.SetEditorFocus();  // WebView Interop
                await Model.ActiveEditor.RestyleEditor();
            }
            catch
            {
                // ignore interop errors
            }
        }
    }).Task.FireAndForget();
}
```

It's quite possible that especially for initialization and activation `async void` calls that aren't truly async might be causing problems in interacting with the WebView. By explicitly ensuring that calls are wrapped into a `Dispatcher.InvokeAsync()` call the activation appears to be reliable. I've not seen any new errors `'Value does not fall within the expected range' Exceptions` since I put this code into production a couple of weeks ago. Older versions still show the errors to the tune of a few every day. We've been running the latest WebView libraries for a while before this, so multiple versions are using the same targets.

This isn't conclusive by any means, but it's definitely encouraging...

**Comment by champnic** [comment]
Aha, that's a great finding @RickStrahl! Can you tell if this moves the execution onto the thread that the WebView2 was created on? WebView2 can only be accessed from it's creation thread so I wonder if that's what was causing this. It's also possible that if the app was in the process of being activated that the message loop wasn't fully spun up to support the WebView2 access. We ran into that issue recently with trying to create a WebView2 during initialization too early.

**Comment by RickStrahl** [comment]
Well the Dispatcher forces execution to the UI thread yes, but regular events -  even async  void one - do that as well. So that alone isn't the issue. But it might be because async void doesn't actually run on a Task that was spawned by WPF that has 'unexpected' behavior when calling async code in the WebView. 

I think a timing issue is more likely. There are a lot of things that work better when tweaking the timing into a Dispatcher (like visibility and and initialization). 

For now though I'm no longer seeing those errors which is pretty likely related to this change which is good news.

**Comment by fvanheeswijk** [comment]
@champnic We are since listening to the ProcessFailed event and can confirm that it is generally working, however in this specific case the ProcessFailed event does not fire. There are also no crash reports in the \WebView2\EBWebView\Crashpad\reports folder.

How can we proceed to debug this? We haven't been able to reproduce it so far :( It seems like the msedgewebview2.exe process simply.. disappears?

**Comment by lggroapa** [comment]
Any update on this issue? Problem reproduced for me, however the occurrence rate seems extremely low.

Runtime: 95.0.1020.30
WinForms Control: 1.0.961.33

Browser.cs(50){Application_ThreadException}: System.ArgumentException: Value does not fall within the expected range.
Browser.cs(50){Application_ThreadException}:    at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller.MoveFocus(COREWEBVIEW2_MOVE_FOCUS_REASON reason)
Browser.cs(50){Application_ThreadException}:    at Microsoft.Web.WebView2.Core.CoreWebView2Controller.MoveFocus(CoreWebView2MoveFocusReason reason)
Browser.cs(50){Application_ThreadException}:    at Microsoft.Web.WebView2.WinForms.WebView2.OnGotFocus(EventArgs e)
Browser.cs(50){Application_ThreadException}:    at System.Windows.Forms.Control.InvokeGotFocus(Control toInvoke, EventArgs e)
Browser.cs(50){Application_ThreadException}:    at System.Windows.Forms.Control.WmSetFocus(Message& m)
Browser.cs(50){Application_ThreadException}:    at System.Windows.Forms.Control.WndProc(Message& m)
Browser.cs(50){Application_ThreadException}:    at Microsoft.Web.WebView2.WinForms.WebView2.WndProc(Message& m)
Browser.cs(50){Application_ThreadException}:    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by RickStrahl** [comment]
So after some more time has passed now I still see these `COREWEBVIEW2_MOVE_FOCUS_REASON` issues show up in my logs even with the Dispatcher mitigation on cross application activation. It's considerably less, which leads me to think that the mitigation works, but there are probably other ways that the control/host can be activated that bypasses  the Dispatcher.

I track all errors in my application and I'm to the point where ~85% of all errors I see are WebView errors.  Granted the number is not huge - I'd say about 5-10 WebView errors per day on a steady userbase of about 1000-1200 daily executions.

I wish I could provide better error info but as said before the problem is that the WebView is not providing a useful stack trace that shows anything outside of the WebView.

I don't want to be a smart ass, but it seems to me looking at what your `MoveFocus()` method does would be a good place to start. If the problem is some sort of invalid input value there should at least be a way to ignore that value and let the control continue to live without moving focus. Anything is better than a hard crash like this...

**Comment by lggroapa** [comment]
@champnic Any chances that this issue is solved in Runtime 100.0.1185.36 and WinForms Control: 1.0.1150.38?

**Comment by champnic** [comment]
@lggroapa No, this is not fixed yet (at least not intentionally by us). But we do have a fix in a PR that will hopefully get checked in soon.

**Comment by champnic** [comment]
This is available for testing in 1.0.1243-prerelease SDK. Thanks!
(Note: This SDK has been deprecated due to compat issues with the StatusBarTextChanged API. See here for more info: https://github.com/MicrosoftEdge/WebView2Feedback/issues/2414#issuecomment-1116335991)

**Comment by Elisa-Adela** [comment]
@champnic Is this solved in 101.0.1210.39? I'm trying to understand the link to #2414.

**Comment by champnic** [comment]
Anything after [1.0.1245.22](https://www.nuget.org/packages/Microsoft.Web.WebView2/1.0.1245.22) should have the fix.

**Comment by BhagvanBT** [comment]
@champnic After taking the latest build(1.0.1343.22).  I am facing the following issue and it is always reproducible.

[2022-09-12 12:02:43.8203 Fatal]  Value does not fall within the expected range.
   at System.StubHelpers.ObjectMarshaler.ConvertToNative(Object objSrc, IntPtr pDstVariant)
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2PrivateHostObjectAsyncMethodContinuation.Invoke(Int32 errorCode, Object& result)
   at Microsoft.Web.WebView2.Core.CoreWebView2PrivateHostObjectHelper.RawHelper.<>c__DisplayClass9_0.<SetAsyncMethodContinuation>b__0()
   at System.Runtime.CompilerServices.TaskAwaiter.<>c__DisplayClass11_0.<OutputWaitEtwEvents>b__0()
   at System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation.<>c__DisplayClass6_0.<GetActionLogDelegate>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by champnic** [comment]
Hey @BhagvanBT - It might make sense to open this in a new issue to track. If you could also add the runtime version you are using, as well as sample code or app that reproduces the issue that would be helpful. Thanks!

**Comment by esenkayaproforce** [comment]
I had same error before. My case was HttpResponse did not match the one I needed.
