### ISSUE TITLE
Touch keyboard not shown for text inputs in UWP

### ISSUE THREAD

**Issue by kitgrose** [MicrosoftEdge/WebView2Feedback#1887]
**Description**
We're experimenting with WebView2 in a UWP app intended to be run under Windows Assigned Access mode and we've so far encountered just two significant bugs. The first is that drop-down menus are not shown (as noted in my comment on #1693), but the second is more significant—the touch keyboard is never shown when an input inside the WebView receives focus.

This happens in all three modes we've tested (regular desktop mode with tablet mode disabled, under tablet mode, and in assigned access mode), and I have not been able to find any workaround.

The app specifies its `PreferredLaunchWindowingMode` as `FullScreen`, but the issue occurs even if we leave full-screen mode and unmaximise the window.
For reference, I'm running WinUI 2.8.0-prerelease.210927001, Edge 95.0.1020.30 on Windows 11 v21H2 (build 22000.258).
**Version**
SDK: WinUI 2.8.0-prerelease.210927001
Runtime: Stable 95.0.1020.30
Framework: UWP
OS: Windows 10 v21H1 (build 19043.1288)

**Repro Steps**
1. Create a new blank UWP app
2. Right click on the project and choose Manage NuGet Packages...
3. Check the "Include prerelease" checkbox and add Microsoft.UI.Xaml v2.8.0-prerelease.210927001
4. Edit `MainPage.xaml` to the following:
```xaml
<Page
    x:Class="TestKeyboardIssue.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:controls="using:Microsoft.UI.Xaml.Controls"
    mc:Ignorable="d"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">

    <controls:WebView2 Source="https://www.bing.com/" />
</Page>
```
5. Build and run on a touch screen device (with or without a keyboard, and with or without the "Show the touch keyboard when not in tablet mode and there's no keyboard attached" setting enabled.
6. Tap in the search field on Bing.com and observe the touch keyboard is not shown (despite the field getting focus).

**Additional context**
One user claims this used to work for them until very recently (perhaps this week), which would imply it was caused by a recent update to Edge. I cannot easily prove or disprove that claim.

[AB#36937317](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/36937317)

**Comment by champnic** [comment]
Hey @kitgrose! This is a known issue that we're testing a fix for right now. I've linked this issue to the bug on our backlog, and we'll let you know when the fix has been deployed. Thanks!

**Comment by mbmleone** [comment]
Is there any update on this? Also interested in solution for this issue.

**Comment by cgladue** [comment]
Yes, this is still happening and would be great to get fixed, any update ?

**Comment by champnic** [comment]
It looks like we have a fix available for testing in runtimes 100.0.1178.0+. You should be able to test this in a few days with the newest Microsoft Edge Dev build.

**Comment by Rajagopal-KG** [comment]
> 

Can you let us know the available date . We could still see 99..0.1150.55 which does not support virtual keyboard in kiosk mode. 
Can we get approximate release date on updated version.

**Comment by champnic** [comment]
The fix should be available in the 100 stable WebView2 Runtime, which will ship sometime in the next week. Thanks!

**Comment by Rajagopal-KG** [comment]
> The fix should be available in the 100 stable WebView2 Runtime, which will ship sometime in the next week. Thanks!

Thank you so much. 

The new version 100.0.1185.29 is now available on the portal. 

We did downloaded the tool and still issue occurs. 
Now we have two errors . Below are the details. 

1. Still virtual keyboard is not launchable with updated version. 
2. While installing the webview2 applicaiton as a fresh installation, the page displays
" Cannot recognize the webview2 to run the application. Please click here to download and install the webview2 runtime environment" 


Kindly help on the issue please. Thanks

**Comment by champnic** [comment]
"We did downloaded the tool and still issue occurs." Can you outline what you did here? You may need to install it as admin to make sure it's a system level install that's accessible to UWP apps.

**Comment by pcbliss** [comment]
I'm still experiencing this issue. I'm running WebView2 104.0.1293.54 in a UWP app. Everything displays fine but it won't bring up the keyboard when tap on an input field. It works properly if I just access the web site directly through Edge. I see this was marked as closed but I'm still seeing the problem.

**Comment by champnic** [comment]
@pcbliss Would you be able to open a new GitHub issue with details about what you are running into? Including things like versions, sample app, etc. will be helpful for us to get a repro as well. Thanks!

**Comment by pcbliss** [comment]
> @pcbliss Would you be able to open a new GitHub issue with details about what you are running into? Including things like versions, sample app, etc. will be helpful for us to get a repro as well. Thanks!

Turns out the problem was that we were setting IsHoldingEnabled = true on the webview2 control, which was preventing the touch keyboard from coming up.

**Comment by champnic** [comment]
Glad you got it figured out!
