### ISSUE TITLE
Webview is blank when used in Wizard window in an VSIX project

### ISSUE THREAD

**Issue by dk511** [MicrosoftEdge/WebView2Feedback#195]
[VSIXProject2.zip](https://github.com/MicrosoftEdge/WebViewFeedback/files/4665127/VSIXProject2.zip)

Attached is the zipped project.

Steps to reproduce the issue.

- Download the above solution and build the it
- Press F5 and open experimental instance of visual studio
- Create a new project
- Type in mywebview2Template and create a project
![image](https://user-images.githubusercontent.com/58889061/82605549-efc93100-9b6a-11ea-95bc-c9ba7c9c2976.png)

- Observe the wizard window is blank, It is expected to load Microsoft site in there. Please let me know if there is a fix for it? So is it that webview2 doesn't work in Project Type = Class Library (VSIX Project)?

[AB#29575864](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/29575864)

**Comment by liminzhu** [comment]
We're getting some help from the VSIX folks. Will get back to you!

**Comment by tinaschrepfer** [comment]
Apologies on the delay. From VS's perspective, extension developers are free to host WebView2 in a tool window themselves, but keep in mind that such feature can be complex and cause performance issues in VS.  However, we are working on the platform support to hosting WebView2 within VS by default (with the date TBD, but within the next year, maybe calendar year).  We are still in the process of discussing the extensibility platform through this, so please stay tuned.

On separate note, are there any requirements/requests you'd like to see the platform support to make things easier for you in the future?

**Comment by rgup63** [comment]
I was trying to host a WPF user control inside a tool window. I got this error. Is there any fix for this issue?
**System.DllNotFoundException: 'Unable to load DLL 'WebView2Loader.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)'**

**Comment by priyasgs** [comment]
> Apologies on the delay. From VS's perspective, extension developers are free to host WebView2 in a tool window themselves, but keep in mind that such feature can be complex and cause performance issues in VS. However, we are working on the platform support to hosting WebView2 within VS by default (with the date TBD, but within the next year, maybe calendar year). We are still in the process of discussing the extensibility platform through this, so please stay tuned.
> 
> On separate note, are there any requirements/requests you'd like to see the platform support to make things easier for you in the future?
@tinaschrepfer ability to host either WPF or Windows Forms based WebView2 in our extensions is absolutely required for us. We have several editors, dialogs, and tool windows in our extension that are now based on the IE control, and would want to migrate to Edge Chromium one.

**Comment by yannduran** [comment]
@priyasgs 

Thanks for pointing this GitHub issue out to me in Gitter! I wasn't aware of it. I also found out the hard way that the `WebView` control wasn't working. I'm disappointed to hear that the `WebView2` control also doesn't work (_yet?_).

@tinaschrepfer 

I also need to host a WPF web control in some of my extensions. I don't need anything all that fancy really, I just need it to work like the `WebBrowser` control. It just has to be able to host web content (pages) and/or display XML data. I'd add my own _forward_/_backward_, _refresh_ etc to my custom tool windows if I require that functionality. 

I don't expect the new control to have all of that functionality baked in, but of course it would be excellent if it did, as long as it was customisable (ie hide/style any buttons etc). But I'd prefer a **working** control without bells & whistles **sooner**, as opposed to having to wait till the end of 2020/2021 for a fully functioning one. 

Having to use a control that is IE-based is really not acceptable in 2020! 3rd paty companies have managed to make a Chromium-based web control that can be added to custom tools windows for VS, so I don't see why Microsoft can't do the same.

I've been on at the team for YEARS now to replace the extremely old IE-based WPF `WebBrowser` control with something more modern'. Its so old that modern sites like Azure DevOps & GitHub often don't display/behave correctly. This is WAY overdue!

I interact with Azure DevOps & GitHub solely through custom tool windows **inside** VS so I don't have to be constantly be _context-switching_ by having to switch over to a browser app, & then find the tab that I want, all  **outside** of VS.

"_within the next year_" or **worse** "_maybe calendar year_" is extremely disheartening to say the least. The `WebBrowser`control really should have been replaced with something that wasn't IE-based back in VS 2017.

**Comment by priyasgs** [comment]
@yannduran sure, yes, my situation is the same. I am trying to replace the old IE control in my extension. I have started a discussion on MSDN too: https://social.msdn.microsoft.com/Forums/en-US/5d5d5e5a-49b4-4ab5-b961-3f694ca8a6a1/hosting-edge-chromium-webview2-in-a-tool-window-in-vsix-extensions?forum=vsx

**Comment by champnic** [comment]
I gave this a try. I'm unfamiliar with VSIX development. It looks like the WebView2Loader.dll is not getting included in the output of the VSIX folder. For example, after building your sample, I see:
`"...\VSIXProject2\bin\Debug\x64\WebView2Loader.dll"`
However, when I look at the folder for the built VSIX, there is no longer the `x64\WebView2Loader.dll`. Any idea how to get that dll to be included when deploying the VSIX?

**Comment by champnic** [comment]
To see the output of the VSIX folder, I opened VSIXProject2 Properties > VSIX > Copy VSIX content to the following location > "output".
![image](https://user-images.githubusercontent.com/45700886/94111960-982d2180-fdf9-11ea-956d-8385eff01803.png)

**Comment by champnic** [comment]
I've got this working now :) There are a couple of things you need to workaround for now. I'm using SDK version **0.9.628-prerelease**.

**WebView2 Targets File**
You need to make a couple of edits to the WebView2 nuget targets file. The exact path of the targets file depends on whether you are installing Nuget using package.config or PackageReferences. In your test app the package was using PackageReferences, and so the target file was here on my machine:
`C:\Users\champnic\.nuget\packages\microsoft.web.webview2\0.9.628-prerelease\build\Microsoft.Web.WebView2.targets`
1. We need to specify that the webview2loader.dll's should be included in the VSIX. To do this, we use the `<IncludeInVsix>true</IncludeInVsix>` property.
2. My machine is 64-bit OS, but my Visual Studio install is x86. To workaround issue #431, I just had the `win-x86` binary get placed into the `x64\` folder.

This is the edited part of the targets file:
```
  <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net' Or ('$(Keyword)' != 'Win32Proj' And '$(TargetFrameworkVersion.TrimEnd(`0123456789.`))' == 'v')">
    <Content Include="$(MSBuildThisFileDirectory)\..\runtimes\win-x86\native\WebView2Loader.dll">
      <Link>x86\%(Filename)%(Extension)</Link>
      <PublishState>Included</PublishState>
      <Visible>False</Visible>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <IncludeInVsix>true</IncludeInVsix>
    </Content>
    <Content Include="$(MSBuildThisFileDirectory)\..\runtimes\win-x86\native\WebView2Loader.dll">
      <Link>x64\%(Filename)%(Extension)</Link>
      <PublishState>Included</PublishState>
      <Visible>False</Visible>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <IncludeInVsix>true</IncludeInVsix>
    </Content>
    <Content Include="$(MSBuildThisFileDirectory)\..\runtimes\win-arm\native\WebView2Loader.dll">
      <Link>arm64\%(Filename)%(Extension)</Link>
      <PublishState>Included</PublishState>
      <Visible>False</Visible>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <IncludeInVsix>true</IncludeInVsix>
    </Content>
  </ItemGroup>
```

Next, you have to specify a UserDataFolder to which you have write permissions. If you don't specify a UserDataFolder, a default one will be created under `C:\Program Files (x86)\...`, and so initialization will fail. I edited the control initialization to use `C:\temp\` as the UserDataFolder with the following:
```
        public UserControl1()
        {
            InitializeComponent();
            InitializeAsync();
        }

        private async void InitializeAsync()
        {
            var env = await CoreWebView2Environment.CreateAsync(null, "C:\\temp");
            webView.EnsureCoreWebView2Async(env);
        }
```

And voila!
![image](https://user-images.githubusercontent.com/45700886/94226032-68d6ed00-feab-11ea-994d-fe2f87171c70.png)

We've fixes #431 which should be in the next prerelease package, and I'll try to get a fix for <IncludeInVsix> as well. I've opened a bug on our end to track. 

Cheers!

**Comment by yannduran** [comment]
That sounds great Nic (complicated but great news). Any chance you could upload a small working solution to GitHub?

**Comment by champnic** [comment]
Unfortunately because it requires changes outside of the solution (to the Nuget WebView2 target file) it's tough to upload a working example. If you have code that you need to figure out the necessary edits for I'd be happy to help. Or if one of the steps was unclear I'd be happy to answer questions and help you make the necessary changes.

**Comment by rgup63** [comment]
> I've got this working now :) There are a couple of things you need to workaround for now. I'm using SDK version **0.9.628-prerelease**.
> 
> **WebView2 Targets File**
> You need to make a couple of edits to the WebView2 nuget targets file. The exact path of the targets file depends on whether you are installing Nuget using package.config or PackageReferences. In your test app the package was using PackageReferences, and so the target file was here on my machine:
> `C:\Users\champnic\.nuget\packages\microsoft.web.webview2\0.9.628-prerelease\build\Microsoft.Web.WebView2.targets`
> 
> 1. We need to specify that the webview2loader.dll's should be included in the VSIX. To do this, we use the `<IncludeInVsix>true</IncludeInVsix>` property.
> 2. My machine is 64-bit OS, but my Visual Studio install is x86. To workaround issue #431, I just had the `win-x86` binary get placed into the `x64\` folder.
> 
> This is the edited part of the targets file:
> 
> ```
>   <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net' Or ('$(Keyword)' != 'Win32Proj' And '$(TargetFrameworkVersion.TrimEnd(`0123456789.`))' == 'v')">
>     <Content Include="$(MSBuildThisFileDirectory)\..\runtimes\win-x86\native\WebView2Loader.dll">
>       <Link>x86\%(Filename)%(Extension)</Link>
>       <PublishState>Included</PublishState>
>       <Visible>False</Visible>
>       <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
>       <IncludeInVsix>true</IncludeInVsix>
>     </Content>
>     <Content Include="$(MSBuildThisFileDirectory)\..\runtimes\win-x86\native\WebView2Loader.dll">
>       <Link>x64\%(Filename)%(Extension)</Link>
>       <PublishState>Included</PublishState>
>       <Visible>False</Visible>
>       <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
>       <IncludeInVsix>true</IncludeInVsix>
>     </Content>
>     <Content Include="$(MSBuildThisFileDirectory)\..\runtimes\win-arm\native\WebView2Loader.dll">
>       <Link>arm64\%(Filename)%(Extension)</Link>
>       <PublishState>Included</PublishState>
>       <Visible>False</Visible>
>       <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
>       <IncludeInVsix>true</IncludeInVsix>
>     </Content>
>   </ItemGroup>
> ```
> 
> **UserControl1 Initialization**
> Next, you have to specify a UserDataFolder to which you have write permissions. If you don't specify a UserDataFolder, a default one will be created under `C:\Program Files (x86)\...`, and so initialization will fail. I edited the control initialization to use `C:\temp\` as the UserDataFolder with the following:
> 
> ```
>         public UserControl1()
>         {
>             InitializeComponent();
>             InitializeAsync();
>         }
> 
>         private async void InitializeAsync()
>         {
>             var env = await CoreWebView2Environment.CreateAsync(null, "C:\\temp");
>             webView.EnsureCoreWebView2Async(env);
>         }
> ```
> 
> And voila!
> ![image](https://user-images.githubusercontent.com/45700886/94226032-68d6ed00-feab-11ea-994d-fe2f87171c70.png)
> 
> We've fixed #431 which should be in the next prerelease package, and I'll try to get a fix for as well. I've opened a bug on our end to track.
> 
> Cheers!

**Hey @champnic **,  I tried all these steps you mentioned here but it doesn't look working at all for VSIX project. Here I am trying to host a webview2 control inside a tool window. Following are the steps I tried, 

1. Added <IncludeInVsix>true</IncludeInVsix> in both the places 
- packages\Microsoft.Web.WebView2.0.9.628-prerelease\build\Microsoft.Web.WebView2.targets to include webview2loader.dll
- packages\Microsoft.Web.WebView2.0.9.628-prerelease\build\native\Microsoft.Web.WebView2.targets
2. Placed win-x86 binary to the x64 folder at this location packages\Microsoft.Web.WebView2.0.9.628-prerelease\build
3. Specified a UserDataFolder at UserControl Initialization

Can you please check and confirm if I am missing anything here? Or if possible , can you please upload a working solution here. Looks like we are doing all the required changes inside the project folder only. In that case you just need to upload your project folder to GitHub.

Thanks

**Comment by champnic** [comment]
Hey @rgup63, we just released a new SDK prerelease package that should have the necessary fixes (shouldn't require changes to targets file and x86/x64 issue). Can you give it a try?
https://www.nuget.org/packages/Microsoft.Web.WebView2/1.0.674-prerelease

If that doesn't work for you, could you provide a repro I can try out? Thanks!

**Comment by champnic** [comment]
I'm going to close this issue as the main issues have been resolved. If this isn't working for anyone for a different reason, please open a new issue. If this isn't working due to one of the following, please let me know and we can reopen this issue if necessary. Thanks!
1. Wrong Loader - resolved by 1.0.674-prerelease.
1. DLL not deployed - resolved by 1.0.674-prerelease.
1. UserDataFolder - need to workaround by specifying writable folder.

**Comment by yannduran** [comment]
@champnic 

This issue should not be closed until NO workarounds are required. Your #3 is still unresolved without a manual workaround.

The trouble with any system that gets used to track issues is that if you close them before they're completely resolved then they become invisible and people will end up creating a new issue for the same problem. 

When you force people to open a new issue context and information simply get lost.

**Comment by champnic** [comment]
Sorry about that, maybe calling it a workaround was a poor choice of words. It's just a necessary part of writing add-ins for both Visual Studio and Office, and will be called out as such in our samples/docs that we plan to write for those scenarios. We aren't currently planning any work to change this behavior.

**Comment by yannduran** [comment]
For a start Visual Studio hasn't supported **_add-ins_** for many years, the extension model is either **VSPackage extensions** or **MEF extensions**. Custom tool windows are provided via VS package extensions.

Custom tool windows in VS are simply wrapped WPF controls. My understanding is that for plain WPF applications there's no such silly workaround/requirement. That being the case, there should be no such requirement for it to work in Visual Studio.

Having written VS extension since 2011 I have NEVER needed to do what you're saying is essential for writing ANY VS extensions ever. If you don't understand VS extension development perhaps ask someone in the VS extensibility team (@madskristensen for example). 

We have been asking for a modern WPF browser control for **many years** now (ie NOT based on IE as is the currently available WPF _WebBrowser_ control).

**Comment by rgup63** [comment]
> Hey @rgup63, we just released a new SDK prerelease package that should have the necessary fixes (shouldn't require changes to targets file and x86/x64 issue). Can you give it a try?
> https://www.nuget.org/packages/Microsoft.Web.WebView2/1.0.674-prerelease
> 
> If that doesn't work for you, could you provide a repro I can try out? Thanks!

Hey @champnic I tried with WebView2 prerelease 1.0.674. Here I got this error. 

![WebView2_error](https://user-images.githubusercontent.com/13938665/96579013-c23c0b80-12f3-11eb-826c-3a6386a6a307.JPG)

I don't understand why is it trying to create a data folder at this location (`C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE`)  instead of a location I specified during WebView2 Environment creation.  
`await CoreWebView2Environment.CreateAsync(null, "C:\\temp");`

As a fix I have given permission to devenv.exe.WebView2 folder and everything looks working. But still my doubt about data folder location is not clear.

**Comment by yannduran** [comment]
This data folder needs to be able to be disabled for cases where all you want to do is display web/xml content.

**Comment by priyasgs** [comment]
@rgup63, that might be because you are setting Source in xaml, in which case we cannot customize the WebView2 initialization (not sure setting CreationProperties property helps). https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.wpf.webview2?view=WebView2-dotnet-1.0.674-prerelease says setting source causes implicit initialization, whereas what we want here is explicit initialization.

**Comment by priyasgs** [comment]
I tried CreationProperties, but that doesn't seem to work with setting Source in XAML as well:
`<wv2:WebView2 Name="webView" Height="500"  Source="https://www.whatismybrowser.com/">
    <wv2:WebView2.CreationProperties>
        <wv2:CoreWebView2CreationProperties UserDataFolder="C:\temp\edgechromium"/>
    </wv2:WebView2.CreationProperties>
</wv2:WebView2>`

**Comment by champnic** [comment]
@rgup63 @priyasgs is correct. Can you confirm whether you were using the Source property? If you are manually creating the environment to set the UserDataFolder you'll need to pass it to `webView.EnsureCoreWebView2Async(env)`;

@priyasgs I've confirmed in a regular WPF app that we have a bug with CreationProperties, where if it gets defined in the XAML as you have it it doesn't work. It does work if instead you define the CreationProperties as a resource:
```
    <Window.Resources>
        <wv2:CoreWebView2CreationProperties UserDataFolder="C:\temp\myFolder" 
                                            x:Key="MyCreationProperties" />
    </Window.Resources>
    <wv2:WebView2
            CreationProperties="{StaticResource MyCreationProperties}"
            .... other attributes />
```
I'll open a new issue and tracking bug for this. My guess is it's related to the order of object creation from the XAML - the Source property gets applied and begins implicit initialization before the CoreWebView2CreationProperties have been created and set to the CreationProperties property.

**Comment by champnic** [comment]
@yannduran I appreciate your passion on this issue. I've created a new GH issue (#553) and workitem on our backlog to track this ask. I'll also reach out to the relevant Office and VS folks to see if they have suggestions on how we can improve this. Thanks!

**Comment by yannduran** [comment]
Thank you Nic! 

Yes I'm extremely passionate about this because as I said it's something we have been asking for for **years**. It's so frustrating that WPF now has a modern replacement control, but that we still can't use it out of the box with a manual step like this.

Does that mean that you're also willing to look into not having to into not having to copy the win-x86 binary to the x64 folder.

Other 3rd-party companies have been able to make a control that works, I don't see why Microsoft can't achieve the same thing.

Thanks again.

**Comment by champnic** [comment]
No worries :) The binary copying should already be fixed with 1.0.674-prerelease - are you finding it's still necessary or you're running into a failure?

**Comment by yannduran** [comment]
I was mainly worried about your statement 

>_It's just a necessary part of writing add-ins for both Visual Studio and Office, and will be called out as such in our samples/docs that we plan to write for those scenarios. **We aren't currently planning any work to change this behavior**._

But I'm currently testing with v1.0.674-prerelease and I'm still getting this error:

![image](https://user-images.githubusercontent.com/2031126/96717845-da468480-13f2-11eb-9d22-efec10a5eb9c.png)

**Comment by champnic** [comment]
That statement was in reference specifically to setting the UserDataFolder, and no longer applies as we've added the item to the backlog and hope to make improvements there 👍 

Your error looks like it's trying to use the old WebView(1) control, not the chromium-based WebView2.

**Comment by yannduran** [comment]
Good catch Nic. I was clicking on a button that a different attempt at integrating a WebView2 control into a tool window had installed.

However, this issue should NOT be closed because even using the v1.0.674-prerelease Nuget package the window still appears blank. No error displayed, even when debugging.

I do not have the dev or canary version of Edge installed or the installer version. And I do not intend to install that just to test out a WebView2 control. The arbitrary decision to block this working in Edge GA is crazy! And yes I know you have "reasons", I just don't agree with them.

So, until the tool window works in the Windows' supplied Edge this issue has not been resolved. Sorry.

**Comment by gpadvorac** [comment]
Its now 4 months later and it seems the WebView2 still has the same problem.  I have a WPF solution which is a little different here, but you would think after 4 months it would be working.  any updates on this?

**Comment by champnic** [comment]
@gpadvorac We are currently actively working on this and hope to have a fix soon. Thanks!

**Comment by yannduran** [comment]
@champnic you had a **manual** workaround that allowed you to load a web page in a tool window installed via a VSIX project back in September 2020.

How is it that almost 5 months later you're still "_currently actively working on this and hope to have a fix soon_"?

All many of us needed was a **SIMPLE** _BrowserWindow_ replacement that could be add to a tool window in a VS extension that just worked out of the box.
