### ISSUE TITLE
WebView2 control not showing in Visual Studio 2015 Toolbox

### ISSUE THREAD

**Issue by kiewic** [MicrosoftEdge/WebView2Feedback#210]
Installing Microsoft.Web.WebView2 0.9.515-prerelease using Visual Studio 2015 Update 3, does not display the WebView2 control in the Toolbox pane.

![image](https://user-images.githubusercontent.com/874134/82840788-a9d0dd80-9e88-11ea-8e23-d145421bdb06.png)

Same package in Visual Studio 2017 does show the WebView2 control in the Toolbox pane.

![image](https://user-images.githubusercontent.com/874134/82840814-c40abb80-9e88-11ea-8500-9eb8e5a56de8.png)

**Bug for VS2019 [done]:** [AB#27485378](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/27485378)
**Bug for VS2015 [done]:** [AB#31769095](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/31769095)

**Comment by djsandb** [comment]
I'm having the same issue with Visual Studio 2019 (up-to-date) and WebView2 0.9.515. I also have Edge Canary installed (version 84.0.524.0).

**Comment by david-risney** [comment]
Thanks! We'll look into this.

**Comment by kiewic** [comment]
Notice that this looks more like a *bug* than a *feature request*, since the documentation indicates that the WebView2 control is listed in the Toolbox, and there is no alternative step for it.

**Comment by rkacharov** [comment]
> I'm having the same issue with Visual Studio 2019 (up-to-date) and WebView2 0.9.515. I also have Edge Canary installed (version 84.0.524.0).

You need a `prerelease` version of the control, please look at here:
https://github.com/MicrosoftEdge/WebViewFeedback/issues/258

**Comment by rkacharov** [comment]
@david-risney is this a `feature request` as currently VS 2017 and above is required? If so, is there a plans of supporting older VS version ?

**Comment by oggy22** [comment]
@kiewic Can you confirm that you are refering to WinForms not WPF? Thank you!

**Comment by kiewic** [comment]
Yes, I'm referring to WinForms.

**Comment by champnic** [comment]
This should be fixed in the latest 1.0.790-prerelease SDK package. Please let me know if you are still running into this. Thanks!

**Comment by ryan-veracitek** [comment]
yep, still seeing this with 1.0.790-prerelease on VS2015. Nothing new in toolbox after NuGet install.

**Comment by champnic** [comment]
@ryan-veracitek Are you able to test if it's broken for you on VS 2019? If it works on 2019, I can open a new bug to specifically track the issue in 2015.

**Comment by ryan-veracitek** [comment]
> @ryan-veracitek Are you able to test if it's broken for you on VS 2019? If it works on 2019, I can open a new bug to specifically track the issue in 2015. (Or if you aren't able to verify in 2019 I can still open the bug)

Yes sir. It worked fine on 2019, but on 2015 it does not.

**Comment by champnic** [comment]
Thanks for verifying! We have some more work planned for 2015 so I'll reopen this issue and update it to say 2015 specifically.

**Comment by ryan-veracitek** [comment]
> Thanks for verifying! We have some more work planned for 2015 so I'll reopen this issue and update it to say 2015 specifically.

Roger that. Thank you for this work. This solves an otherwise much more difficult issue for one of our clients so I'm sure glad there's a team at MS working on this. The "hybrid" concept has been working great in many scenarios for years with the webbrowser control and this isn't too far from a drop-in replacement. Hopefully at some point it won't even require a runtime distributed to function?

**Comment by champnic** [comment]
Thanks! The control will always require a runtime, but we're working hard to make it so app devs don't have to be the ones distributing/installing it themselves. You can track that work (and some passionate discussion) in #348 and #341.

**Comment by champnic** [comment]
All bugs in this thread should now be fixed in 1.0.865-prerelease SDK package. Please let me know if you run into any further issues. Thanks!
