### ISSUE TITLE
WebView2 crashed unexpectedly

### ISSUE THREAD

**Issue by fvanheeswijk** [MicrosoftEdge/WebView2Feedback#2132]
**Description**
The WebView2 browser crashed unexpectedly. We have a minidump available at [4b76b2ac-2d09-4b18-a01f-b1388df44d37.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/7995886/4b76b2ac-2d09-4b18-a01f-b1388df44d37.zip).

**Version**
SDK: 1.0.1054.31
Runtime: Unknown, but recent stable release, crash was on 20-12-2021
Framework: WinForms
OS: Win 10

**Repro steps**
Unsure how to reproduce, it happened randomly.

[AB#38041461](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/38041461)

**Comment by fvanheeswijk** [comment]
We also have a second minidump available from SDK 1.0.961.33 in case you are still interested in it:
[1082828f-de9a-47a6-93cf-c767df445628.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/7995982/1082828f-de9a-47a6-93cf-c767df445628.zip), that crash was with a stable release on 07-12-2021.

**Comment by champnic** [comment]
Thanks for the bug and crash dumps @fvanheeswijk - I've added this to our backlog to take a look!

**Comment by nabils** [comment]
We are seeing this too. Any update? Any way to recover/get more detail from these crashes. We get a black screen on all webview renderers and no logs at all. User has to restart whole app to recover. Has happened twice this week.

SDK: 1.0.1054.31
Runtime: 94.0.992.50
Framework: WPF
OS: Win 10

**Comment by champnic** [comment]
@nabils "We are seeing this too." Are you looking at the crash logs and have verified it's the same issue? Or are you just seeing a crash in general?

You should be able to listen to the `ProcessFailed` event to listen for crashes, and can choose to recreate the WebView2 without restarting the whole app. You can also check for crash dumps in your app's `<userDataFolder>\EBWebView\crashpad\reports` folder. Thanks!

**Comment by cole-rob** [comment]
I don't know if what I'm seeing is the same issue.  I get a crash after running scripts on an html page a number of times (usually between 20 and 34 times).  A script will work correctly and then at some point, WebView2 crashes and the program closes.  EBWebVIEW\crashpad\reports is empty.  ProcessFailed event never triggers.  If I run from VS2022, I see: "The program '[3592] WebView_Example.exe' has exited with code 2147483651 (0x80000003)."

**Comment by champnic** [comment]
Hey @cole-rob - Without crash info this will be hard to investigate. Do you have a sample app that can reproduce this issue?

**Comment by lingamy** [comment]
@fvanheeswijk , I looked at the dumps you provided above, it seems to be fixed in Edge/WebView2 98 which was released on 2/3. If this repros for you for WebView2 runtime 98 or later, could you please collect a dump and share with us?

**Comment by champnic** [comment]
Closing as we believe these crashes in particular have been resolved in the runtime. Please let me know if you see this again. Thanks!

**Comment by cole-rob** [comment]
I am still seeing this problem after updating to the newest version.

I have been away (moving to a new house) and will post my test code as soon as I put it all in one solution (some of it displays an html file in another location).

**Comment by cole-rob** [comment]
Figured I would let you know that the problem I was seeing in my last message was with nuget version 1.0.1185.39-prerelease.
Today I updated to 1.0.1222-prerelease and I have not been able to reproduce the issue.  Thank you for looking into this.

**Comment by champnic** [comment]
@cole-rob Glad to hear it's working! (And congrats on the new house - hope the move went well :) )

**Comment by CenturionYun** [comment]
@champnic When will 1.0.1222-prerelease be production release? The release note page https://docs.microsoft.com/en-us/microsoft-edge/webview2/release-notes is messed up, it's very hard to figure out when the fixes in prerelease will be in which prod release.

**Comment by champnic** [comment]
Looks like the code just missed a cutoff deadline, so will likely be in the next prerelease package, and then the following release package (around end of June).

I agree it's very difficult to figure out exactly when something will ship in stable/release. Typically if it's in a prerelease package it will be in the following release package, although as I just noted that wasn't the case here. We're planning some work to make tracking fixes and release more clear in the future. Thanks!

**Comment by jsclough** [comment]
Discovered this crash was caused by opening a modal window without handling attempted reentrancy as I was assisted with here:

https://github.com/MicrosoftEdge/WebView2Feedback/issues/2542
