### ISSUE TITLE
PDF View is not raising the correct events for links

### ISSUE THREAD

**Issue by cbra-caa** [MicrosoftEdge/WebView2Feedback#239]
### Setup
- WPF application
- .Net 4.7.2
- 0.9.579-prerelease package for WebView
- Edge Dev installed

### Problem
I have found some problems with links in pdf's displayed in WPF with the new WebView. I have a listener on _NavigationStarting_ which then uses _IsUserInitiated_ to determine if the program or the user made the navigation. If it was the latter (the user) I then open the link externally.

1. When the user clicks on a normal http:// link the _CoreWebView2NavigationStartingEventArgs_ will report that the _IsUserInitiated_ is **false**. 
I expected this to be **true**.

2. When a link points to an external protocol **myProtocol://somewhere** the _NavigationStarting_  handler is never raised, and nothing happens. If you right-click on the link and select "Open link in new window" a new empty window will spawn, and then ask if you want to open the link in the external program.
I excepted this to either hit the _NavigationStarting_ or _PermissionRequested_ handlers.

3. When opening a link via 'Open in new window' in the context menu the _NewWindowRequested_ handler does not fire.
I expected that _NewWindowRequested_ was raised.

None of these problems are present when displaying webpages.

### Code
**MainWindow.xaml**
```
<Window x:Class="TestWebView2App.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:wv2="clr-namespace:Microsoft.Web.WebView2.Wpf;assembly=Microsoft.Web.WebView2.Wpf"
        mc:Ignorable="d"
        Title="MainWindow" Height="800" Width="1000">

  <Grid>
    <Grid.RowDefinitions>
      <RowDefinition Height="Auto" />
      <RowDefinition Height="*" />
      <RowDefinition Height="Auto" />
    </Grid.RowDefinitions>

    <Button Content="Navigate back to pdf"
            Click="Button_Click" />

    <wv2:WebView2 Name="WebView"
                  Grid.Row="1"
                  Source="locationOfLinkExamples.pdf" />

    <ScrollViewer Height="150"
                  Grid.Row="2">
      <TextBox x:Name="WebViewEvents" 
               Text="*** EVENT OVERVIEW ***"
               Foreground="OrangeRed"
               Background="Black"
               IsReadOnly="True" />
    </ScrollViewer>

  </Grid>
</Window>
```

**MainWindow.xaml.cs**
```
using System;
using System.Windows;

namespace TestWebView2App
{
  public partial class MainWindow : Window
  {
    public MainWindow()
    {
      InitializeComponent();

      WebView.CoreWebView2Ready += WebView_CoreWebView2Ready;
    }

    private void WebView_CoreWebView2Ready(object sender, EventArgs e)
    {
      WebView.CoreWebView2.NavigationStarting += CoreWebView2_WebView_NavigationStarting;
      WebView.CoreWebView2.NewWindowRequested += CoreWebView2_NewWindowRequested;
      WebView.CoreWebView2.PermissionRequested += CoreWebView2_PermissionRequested;
      pdfAddress = WebView.Source;
    }

    private void CoreWebView2_PermissionRequested(object sender, Microsoft.Web.WebView2.Core.CoreWebView2PermissionRequestedEventArgs e)
    {
      WebViewEvents.Text += Environment.NewLine + $"Requesting permission for '{e.Uri}', is from user: '{e.IsUserInitiated}'";
    }

    private void CoreWebView2_NewWindowRequested(object sender, Microsoft.Web.WebView2.Core.CoreWebView2NewWindowRequestedEventArgs e)
    {
      WebViewEvents.Text += Environment.NewLine + $"New window requested for '{e.Uri}', is from user: '{e.IsUserInitiated}'";
    }

    private void CoreWebView2_WebView_NavigationStarting(object sender, Microsoft.Web.WebView2.Core.CoreWebView2NavigationStartingEventArgs e)
    {
      WebViewEvents.Text += Environment.NewLine + $"Navigation to '{e.Uri}', is from user: '{e.IsUserInitiated}'";
    }

    private Uri pdfAddress = new Uri("http://google.com");
    private void Button_Click(object sender, RoutedEventArgs e)
    {
      WebView.Source = pdfAddress;
    }
  }
}
```

### How to reproduce
1. Download the example pdf
2. Change the path of locationOfLinkExamples.pdf to wherever the pdf is located
3. Start the program
4. Click the first link, observe that IsUserInitiated is **false**
5. Click the second link, observe that no events are sent
6. Right click the first link and select 'Open link in new window', 
observe that no events are sent even though a new window opens
7. Right click the second link and select 'Open link in new window', 
observe that no events are sent even though a new window opens

_OBS: On my computer the protocol mp is associated with an application and works without problem when accessed through the edge browser normally._

[LinkExamples.pdf](https://github.com/MicrosoftEdge/WebViewFeedback/files/5108463/LinkExamples.pdf)

[AB#28648750](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/28648750)

**Comment by champnic** [comment]
This has been fixed in the latest WebView2 Runtime, 88.0.705.50+. Please let me know if you are still running into this issue and I can reactivate. Thanks!

**Comment by cbra-caa** [comment]
@champnic  
I can still reproduce this issue, with the same code as above
WebView2 version: 1.0.790-prerelease
Edge: 89.0.774.34 (Official build) beta (64-bit)

![image](https://user-images.githubusercontent.com/47817657/109151917-1441e180-776b-11eb-9967-f95f1f6dafc7.png)

Currently it looks like the **IsUserInitiated** is inverted, as I get **true** when pressing the navigation button in the top of the window, and **false** when using the link in the .pdf file.

**Comment by champnic** [comment]
Our linked bug is still open, sorry! I may have closed this one by accident, thanks for verifying.

**Comment by cbra-caa** [comment]
@champnic 
Any news on this one? Just tested with the newest version, and the results are still the same

WebView: 1.0.902
Edge Evergreen: 91.0.864.48

**Comment by champnic** [comment]
I'm reaching out to the bug owner to get more info on status, thanks!

**Comment by cbra-caa** [comment]
@champnic 
Any news on this one? I just tested it and the same problems persists.

WebView: 1.0.1462.37
Edge: 108.0.1462.54

**Comment by crutkas** [comment]
This bug is affecting powertoys
