### ISSUE TITLE
CoreWebView2PdfToolbarItems lacks members for "enter full screen" and "Settings and more"

### ISSUE THREAD

**Issue by JohnThomson** [MicrosoftEdge/WebView2Feedback#2728]
I want to write something like

```
myWevView2.CoreWebView2Settings.HiddenPdfToolbarItems = CoreWebView2PdfToolbarItems.FullScreen|CoreWebView2PdfToolbarItems.Settings;
```
but there are no members in the enumeration that correspond to these buttons, as far as I can see.

And the "Enter full screen" button is one I would particularly like to remove. It doesn't do the expected thing...the PDF only expands to fill the WebView2, not the whole screen, and the scroll bar is lost...and there's no obvious way to get the toolbar back, which would be very confusing for our users.

[AB#41240616](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/41240616)

**Comment by JohnThomson** [comment]
![Problem toolbar buttons](https://user-images.githubusercontent.com/1360521/187347617-490a3717-8055-4545-9e33-62fd8f186a50.png)
Shows the buttons I want to hide

**Comment by champnic** [comment]
This should be fixed in the latest SDK update. Thanks!

**Comment by JohnThomson** [comment]
Thanks!

**Comment by superware** [comment]
Is there a reason this still doesn't work as of June 2023? Thanks.

**Comment by champnic** [comment]
@superware What SDK and runtime version are you seeing this broken on? @ElyssaJyu FYI

**Comment by ElyssaJyu** [comment]
Hi @superware, I apologize for the inconvenience, but currently, it seems that hiding the `FullScreen` and `MoreSettings` items on the PDF toolbar isn't functioning as expected. I'm actively working to resolve this issue.

**Comment by ElyssaJyu** [comment]
Hi @superware, I'm working on the issue currently. Will post here when the fix is available soon

**Comment by sawork** [comment]
And now the year 2026 is coming )))

**Comment by ElyssaJyu** [comment]
add @prija-microsoft for viz, thanks
