### ISSUE TITLE
CoreWebView2_ProcessFailed event ExitCode: '-2147483645

### ISSUE THREAD

**Issue by Elisa-Adela** [MicrosoftEdge/WebView2Feedback#2747]
**Description**
I have a WinForms application using WebView2 and WebView Runtime fixed version.
There are several windows that are initialized.
After upgrade sometimes the application crashes. at startup.

{CoreWebView2_ProcessFailed}: Object ID 7 Thread 7 - ServiceDocumentation: CoreWebView2_ProcessFailed
{CoreWebView2_ProcessFailed}: SDS error 11504: CoreWebView2_ProcessFailed event ExitCode: '-2147483645', Reason: 'Unexpected', ProcessDescription: '', ProcessFailedKind: 'BrowserProcessExited', FrameInfosForFailedProcess: ''
263

**Version**
SDK: 
Runtime: 
Framework: 
OS: 

**Repro Steps**
        {OnNavigationStarting}
	{CoreWebView2_WebResourceRequested}
	{OnSourceChanged}
	{OnNavigationCompleted}
	{OnDocumentReady}
	{OnDocumentReady}
	{OnDocumentReady}: Object ID 7 Thread 7 - ServiceDocumentation: Executing queued scripts
        {OnNavigationCompleted}: Object ID 7 Thread 7 - ServiceDocumentation: Keyboard listeners attached to browser window.
	{Hide}: Window 'ServiceDocumentation' is already hidden, ignoring Hide call
	{ExecuteEventLater}: Object ID 7 Thread 7 - ServiceDocumentation: Event received, invoking later 'Microsoft.Web.WebView2.Core.CoreWebView2ProcessFailedEventArgs'
	{CoreWebView2_ProcessFailed}: Object ID 7 Thread 7 - ServiceDocumentation: CoreWebView2_ProcessFailed

Screenshot from data dump:
![image](https://user-images.githubusercontent.com/8292558/188075877-e2d8eda3-7524-448c-9d0e-27d98e55b4d6.png)

**Additional context**

**Comment by LiangTheDev** [comment]
Thanks for reporting the issue and providing the stack of the crash. This is a known issue. We are working on it. Hopefully it can be fixed soon.
One of the conditions for triggering the crash is that a site without favicon. If you are actually navigating to local content or a site that you control, you could workaround the issue by adding favicon.ico at the root of the site.

**Comment by Elisa-Adela** [comment]
Thanks.
I do not have means to add the favicon on some sites.
I tried some workarounds in webresourcerequested(), but they are not working.
Which latest version does not have this issue?

**Comment by LiangTheDev** [comment]
The fix currently is not released yet in any channel. It should be in next Edge Canary build to be released today or tomorrow.

I'll see whether we could make the fix available in stable channel faster. If we could not, the fix will be in Edge WebView2 runtime 107, scheduled to be released at the end of October.

**Comment by Elisa-Adela** [comment]
The last delivery that hasn't got this issue is 1.0.1210.39 with 101.0.1210.53.
Maybe it helps.

**Comment by LiangTheDev** [comment]
The fix is in Edge Canary now. If you want to try it out:

- Download and install Edge Canary from https://www.microsoftedgeinsider.com/en-us/download/canary
- Set environment variable WEBVIEW2_RELEASE_CHANNEL_PREFERENCE with value of 1
- Rerun the application

**Comment by Elisa-Adela** [comment]
@LiangTheDev Is the fix available on 107.0.1418.35?

**Comment by sln162** [comment]
@LiangTheDev On Win7, WebView2: 107.0.1418.62. This problem is still encountered. If the website has an icon, but it is not in the root directory, will it be repaired?

**Comment by LiangTheDev** [comment]
Is it the same crashing stack? Our telemetry data indicates that the issue has been fixed.

**Comment by sln162** [comment]
Currently, it does not appear again (SDK has been updated to 1.0.1462.37)

**Comment by sln162** [comment]
`[webview2]ExitCode = -2147483645|ProcessDescription = |ProcessFailedKind = RenderProcessExited|Reason = Crashed|108.0.1462.54|6.1.7601.65536`
`[webview2]ExitCode = -2147483645|ProcessDescription = |ProcessFailedKind = BrowserProcessExited|Reason = Unexpected|108.0.1462.46|6.1.7601.65536`
@LiangTheDev   After querying the background data, I found that the error was reported almost every day. The IP addresses were different, but it seemed that the OS version was all win7. Is this problem not solved for win7?

**Comment by Elisa-Adela** [comment]
I've integrated 108.0.1462.46 two weeks ago and so far we do not have the problem anymore, OS Win10

**Comment by LiangTheDev** [comment]
@sln162 there are a lot of renderer process crashes and some browser process crashes, the exit code itself doesn't tell us which stack the crash happened. We should be able to recover from the crashes by retry (reload the page or recreate webview). We also collect data for the crashes and fix them with priority aligned with hits. If you want to figure out a specific crash, please look into the *.dmp files under EBWebView\Crashpad\reports subfolder of the webview2 user data folder.

**Comment by sln162** [comment]
@LiangTheDev   Thank you for reminding us that when the process crashes, we will delay retrying several times except for OutOfMemory reasons, because a month or two ago, the error code -2147483645 failed to retry many times, so we excluded it, and now we Rejoin and continue to observe later.
