### ISSUE TITLE
The open file dialog box no longer opens.

### ISSUE THREAD

**Issue by PCRacer** [MicrosoftEdge/WebView2Feedback#3075]
**Description**
After upgrading webview2 to version 108.0.1462.46 or higher, running our program in an administrator account(the default built-in Administrator Account that needs activation - [net user administrator /active:yes]), the open file dialog box no longer opens. Only the save dialog opens but not the open dialog, on any website or inside any logged-in account.

It simply ignores the open dialog call. When running our application on a non-administrative account, it runs normal, and the open dialog opens as usual.

**Version**
SDK: 1.0.1.1462.37
Runtime: 108.0.1462.46+
Framework: Win32 / Delphi 10.3
OS: Windows 7 SP1 Ultimate - v6.1.7601  - 64 bit (Fully Updated - December 2022)

**Repro Steps**
Simply running our application on an administrator account, the application refuses to run the open dialog.

Navigating to our homepage and trying to open a saved file, it refuses to work.

Or

1. visit https://www.google.com, click 'search by image'
2. then click on the "Search by Image" icon
3. then select the "upload a file" link to open the file dialog to select an image. The open file dialog does not open.

**Screenshots**

**Additional context**
[SSuiteNetSurferPortable.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/10253571/SSuiteNetSurferPortable.zip)

[AB#42772842](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/42772842)

**Comment by victorthoang** [comment]
Hello @PCRacer,

Thanks for your bug report. I've assigned this to a dev that can best try to replicate the issue and follow up on this. With holidays over and new year's approaching, I appreciate your patience!

Victor

**Comment by LiangTheDev** [comment]
I can repro the issue. The issue is now tracked internally.

**Comment by PCRacer** [comment]
Thank you so very much... :D

**Comment by tofuandeve** [comment]
Hi @PCRacer The issue is fixed and file dialog admin mode should work for win7 in v109. Thank you!

**Comment by PCRacer** [comment]
Thank you...

...which exact edition are you referring to? as in the current edition of WebView2 ( 109.0.1518.52 ) , it still does not work!

................

**Comment by PCRacer** [comment]
Thank you so very much for the feedback, much appreciated... :D

**Comment by PCRacer** [comment]
The WebView2 control just updated to 109.0.1518.61 and the problem has been corrected.

Thank you so very much for your time and effort... :) ... :)
