### ISSUE TITLE
Element not found. (0x80070490) when using host objects

### ISSUE THREAD

**Issue by fvanheeswijk** [MicrosoftEdge/WebView2Feedback#335]
So this issue will be more difficult to debug as we so far have not been able to reproduce it.

When we call `$WF.handler.systemIdentification()` we get the following error:

> VM6:1 Uncaught Error: Element not found. (0x80070490)
>     at RemoteMessenger.postSyncRequestMessage (<anonymous>:1:10471)
>     at Function.applyHostFunction (<anonymous>:1:22650)
>     at Object.apply (<anonymous>:1:15398)
>     at <anonymous>:1:15

However `window.chrome.webview.hostObjects.sync.handler.systemIdentification()` works correctly with no issues.

Furthermore, `$WF.handler` is defined as follows:

```
window.$Events = {
	'on': function (evs, sel, dat, han) {
		$(this).on (evs, sel, dat, han);
		return this;
	},

	'off': function (evs, sel, han) {
		$(this).off (evs, sel, han);
		return this;
	},

	'trigger': function (ev, par) {
		$(this).triggerHandler (ev, par);
		return this;
	}
};

window.$WF = $.extend ({}, $Events);

(function () {
	var external = null;

	try {
		// MS WebView2 has both window.external and this one; we want this one first
		external = window.chrome.webview.hostObjects.sync.handler;
	} catch (e) {
	}
	external = external || window.external;

	Object.defineProperties ($WF, {
		'handler': {
			get: function () {
				return external;
			},
			configurable: false
		}
	});
}) ();
```

`systemIdentification` is defined as follows:

```
public delegate string SystemIdentificationHandler();

[ComVisible(true)]
public class ExternalDocHostUICallback : DocHostUICallback
{
	public event SystemIdentificationHandler SystemIdentification;

	[ComVisible(true), DispId(1000)]
	public string systemIdentification ()
	{
		if (SystemIdentification == null)
			return "";

		return SystemIdentification();
	}
}
```

And later on we add an event to it, but that shouldn't be an issue.

We also get different error messages when we either call a different (non-existent) function or we pass an invalid number of parameters, so it should be the correct function/method we are calling.

We have tried to reproduce this issue but have not been successful in a test project, can you give us any hints on how to continue debugging this? We are particularly surprised by the fact that `window.chrome.webview.hostObjects.sync.handler.systemIdentification()` works but `$WF.handler.systemIdentification()` does not and this appears to be one of the only functions/methods that is not working, other ones that we are using do work.

[AB#27803563](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/27803563)

**Comment by pagoe-msft** [comment]
@fvanheeswijk,

Thanks for bringing this to our attention! I've filed a bug and we will investigate.

**Comment by champnic** [comment]
@fvanheeswijk Has this error only hit once and typically the code works fine? Or does it fail in some environment, for example, and you are unable to reproduce the issue locally?

**Comment by fvanheeswijk** [comment]
@champnic This issue reproduces 100% of the time in our actual application and also for multiple developers, the only thing we cannot get it to do is to reproduce within a test project.

**Comment by fvanheeswijk** [comment]
I just found this topic on Stackoverflow: https://stackoverflow.com/a/62804535

Is this still the case? Our class is marked with `ComVisible(true)` but with nothing else, also I haven't found anything regarding those attributes in the documentation?

**Comment by champnic** [comment]
We have a task to improve our documentation here for .NET.

We looked into this issue a bit and we don't think it's related to your host object - rather the JS garbage collector at some point decides to clean up the host object which removes it on the host side as well, and so calling the host object function results in the element not found error. As noted, the workaround is to always use the full `window.chrome.webview.hostObjects.sync.handler.systemIdentification()`

We're going to keep digging and see if we can fix the GC issue with the host objects.

**Comment by cgeier** [comment]
Here's some documentation regarding COM that you may find useful:

- [Introducing the Class Interface](https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-4.0/4fcadw4a(v=vs.100))

- [Qualifying .NET Types for Interoperation](https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-4.0/7fcfby2t(v=vs.100))

- [ComVisibleAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.comvisibleattribute?redirectedfrom=MSDN&view=netcore-3.1)

- [InterfaceTypeAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.interfacetypeattribute?redirectedfrom=MSDN&view=netcore-3.1)

- [Exported Type Conversion](https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-4.0/46f8ac6z(v=vs.100)?redirectedfrom=MSDN) 

- [Setting an object from .NET to JavaScript code through WebView2
](https://stackoverflow.com/questions/62794609/setting-an-object-from-net-to-javascript-code-through-webview2/62804535#62804535)

**Comment by pagoe-msft** [comment]
Hi Everyone,

This was addressed in the [1.0.707-prerelease version](https://docs.microsoft.com/en-us/microsoft-edge/webview2/releasenotes#10707-prerelease).

**Comment by bruno-walter** [comment]
I'm still seeing this on 1.0.721-prerelease. Using the full window.chrome.webview.hostObjects.sync. to access my object resolves it so I'm pretty sure it's the same issue.

**Comment by cgeier** [comment]
@fvanheeswijk,@champnic I did some testing and I think that I may have found the issue when using the code posted above (which I'm re-posting below):

```
window.$Events = {
	'on': function (evs, sel, dat, han) {
		$(this).on (evs, sel, dat, han);
		return this;
	},

	'off': function (evs, sel, han) {
		$(this).off (evs, sel, han);
		return this;
	},

	'trigger': function (ev, par) {
		$(this).triggerHandler (ev, par);
		return this;
	}
};

window.$WF = $.extend ({}, $Events);

(function () {
	var external = null;

	try {
		// MS WebView2 has both window.external and this one; we want this one first
		external = window.chrome.webview.hostObjects.sync.handler;
	} catch (e) {
	}
	external = external || window.external;

	Object.defineProperties ($WF, {
		'handler': {
			get: function () {
				return external;
			},
			configurable: false
		}
	});
}) ();

```

The issue occurs at this statement:  `window.$WF = $.extend ({}, $Events);` when adding the above code with `AddScriptToExecuteOnDocumentCreatedAsync`. The error is `$ is not defined` which can be seen if you change the code:

**Original:**
```
window.$WF = $.extend({}, $Events);

```

**Change To**:
```
try {
	window.$WF = $.extend({}, $Events);
}
catch (e) {
	window.chrome.webview.postMessage('Error: (msg 1b2): ' + e.message);
}

```

**Result**: `$ is not defined`

The most likely cause is trying to run the code above using 'AddScriptToExecuteOnDocumentCreatedAsync' which must be called before the WebView2 Source property is set. Attempting to use 'AddScriptToExecuteOnDocumentCreatedAsync` after the Source property has been set, has no effect. Attempting to use `AddScriptToExecuteOnDocumentCreatedAsync`  in `DOMContentLoaded` (or later event handlers such as `NavigationComplete`) will have no effect--the event that causes the code specified in  `AddScriptToExecuteOnDocumentCreatedAsync` to run has already occurred. Finally, `$` won't be defined until `DOMContentLoaded` has occurred. 

**Here's a solution that seems to work:**

**JavaScript1.js**

**Note**:  For `JavaScript1.js` need to set **BuildAction** property to **Embedded Resource**.

- On VS menu, click **View**
- Select **Solution Explorer**
- On VS menu, click **View**
- Select **Properties Window**
- In Solution Explorer, click **JavaScript1.js**
- In Properties Window, click area next to **Build Action**, set value to **Embedded Resource**


```
window.chrome.webview.postMessage('msg 1a');

window.$Events = {
	'on': function (evs, sel, dat, han) {
		$(this).on(evs, sel, dat, han);
		return this;
	},

	'off': function (evs, sel, han) {
		$(this).off(evs, sel, han);
		return this;
	},

	'trigger': function (ev, par) {
		$(this).triggerHandler(ev, par);
		return this;
	}
};

window.chrome.webview.postMessage('msg 1b');

try {

	window.$WF = $.extend({}, $Events);

	window.chrome.webview.postMessage('msg 1b1');
}
catch (e) {
	window.chrome.webview.postMessage('Error: (msg 1b2): ' + e.message);
}


window.chrome.webview.postMessage('msg 1c');
(function () {

	window.chrome.webview.postMessage('msg 1d');
	var external = null;

	try {
		// MS WebView2 has both window.external and this one; we want this one first
		external = window.chrome.webview.hostObjects.sync.handler;

		window.chrome.webview.postMessage('msg 1e');
	} catch (e) {
		window.chrome.webview.postMessage('Error: ' + e.message);
	}

	window.chrome.webview.postMessage('msg 1f');
	external = external || window.external;

	window.chrome.webview.postMessage('msg 1g');

	Object.defineProperties($WF, {
		'handler': {
			get: function () {
				window.chrome.webview.postMessage('msg 1h');
				return external;
			},
			configurable: false
		}
	});

	window.chrome.webview.postMessage('msg 1i');
})();
window.chrome.webview.postMessage('msg 1j');

```

**ExternalDocHostUICallback.cs**

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Runtime.InteropServices;
using System.Diagnostics;

namespace WebView2HostObjectsTest
{
    [ComVisible(false)]
    public delegate string SystemIdentificationHandler();

    [ComVisible(false)]
    public delegate void SystemIdentificationValueUpdatedHandler(object sender, SystemIdentificationValueUpdatedEventArgs e);

    [ComVisible(true)]
    [InterfaceType(ComInterfaceType.InterfaceIsIDispatch)]
    public interface IComEventsExternalDocHostUICallback
    {
        [DispId(10000001)]
        string SystemIdentification();

        [DispId(10000002)]
        void SystemIdentificationValueUpdated(object sender, SystemIdentificationValueUpdatedEventArgs e);

    }

    [ComVisible(true)]
    [InterfaceType(ComInterfaceType.InterfaceIsIDispatch)]
    public interface IExternalDocHostUICallback
    {
        [DispId(00000001)]
        string systemIdentification();

        [DispId(00000002)]
        void SendUpdates(string data);
    }

    [ComVisible(true)]
    [ClassInterface(ClassInterfaceType.None)]
    [ComSourceInterfaces(typeof(IComEventsExternalDocHostUICallback))]
    public class ExternalDocHostUICallback : IExternalDocHostUICallback
    {
        public event SystemIdentificationHandler SystemIdentification;
        public event SystemIdentificationValueUpdatedHandler SystemIdentificationValueUpdated;

        public string systemIdentification()
        {
            if (SystemIdentification == null)
                return "";

            return SystemIdentification();
        }

        public void SendUpdates(string data)
        {
            //Important: it's necessary to check if there are any subscribers
            //before raising an event
            if (SystemIdentificationValueUpdated != null)
            {
                //create new instance
                SystemIdentificationValueUpdatedEventArgs valueArgs = new SystemIdentificationValueUpdatedEventArgs(data);

                //raise event
                SystemIdentificationValueUpdated(this, valueArgs);
            }
        }
    }

    [ComVisible(true)]
    public class SystemIdentificationValueUpdatedEventArgs : System.EventArgs
    {
        public string Data { get; set; } = string.Empty;
        public SystemIdentificationValueUpdatedEventArgs(string data)
        {
            this.Data = data;
        }
    }
}

```

**HelperLoadResource.cs**

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.IO;
using System.Reflection;
using System.Diagnostics;

namespace WebView2HostObjectsTest
{
    public static class HelperLoadResource
    {
        public static string ReadResource(string filename)
        {
            //use UTF8 encoding as the default encoding
            return ReadResource(filename, Encoding.UTF8);
        }

        public static string ReadResource(string filename, Encoding fileEncoding)
        {
            string fqResourceName = string.Empty;
            string result = string.Empty;

            //get executing assembly
            Assembly execAssembly = Assembly.GetExecutingAssembly();

            //get resource names
            string[] resourceNames = execAssembly.GetManifestResourceNames();

            if (resourceNames != null && resourceNames.Length > 0)
            {
                foreach (string rName in resourceNames)
                {
                    if (rName.EndsWith(filename))
                    {

                        //set value to 1st match
                        //if the same filename exists in different folders,
                        //the filename can be specified as <folder name>.<filename>
                        //or <namespace>.<folder name>.<filename>
                        fqResourceName = rName;

                        //exit loop
                        break;
                    }
                }

                //if not found, throw exception
                if (String.IsNullOrEmpty(fqResourceName))
                {
                    throw new Exception($"Resource '{filename}' not found.");
                }

                //get file text
                using (Stream s = execAssembly.GetManifestResourceStream(fqResourceName))
                {
                    using (StreamReader reader = new StreamReader(s, fileEncoding))
                    {
                        //get text
                        result = reader.ReadToEnd();
                    }
                }
            }

            return result;
        }

    }
}

```

Here are 2 demo projects. One that doesn't work, and one that works. To use the demo projects ensure that `PackageManagement` is set to `PackageReference` prior to opening them.

- On VS menu, select **Tools**
- Select **Options**
- Expand **NuGet Package Manager**
- Click **General**
- Under **Package Management**, set **Default package management format: ** to **PackageReference**


**Resources**
[How to read embedded resource text file](https://stackoverflow.com/questions/3314140/how-to-read-embedded-resource-text-file)
