### ISSUE TITLE
PrintAsync Function Bug

### ISSUE THREAD

**Issue by clayzzzzzzzzzz** [MicrosoftEdge/WebView2Feedback#3379]
**Description**
If the printer name contains Chinese or full width spaces, the PrintAsync function will fail.
Here is my code:
CoreWebView2PrintSettings printSettings = webView.CoreWebView2.Environment.CreatePrintSettings();
printSettings.PrinterName = "HP LaserJet 400 M401 PCL6 Class Driver(副本1)";
CoreWebView2PrintStatus printStatus = await webView.CoreWebView2.PrintAsync(printSettings);
printStatus will be OtherError.

**Version**
SDK: Microsoft.Web.WebView2 v1.0.1722.32
Runtime: C# .NET Framework 4.6.1
Framework: WinForms
OS: Win10

[AB#44135146](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/44135146)

**Comment by novac42** [comment]
Thanks for reporting the issue. I've assigned this to a dev that can help follow up on this.

**Comment by monica-ch** [comment]
@clayzzzzzzzzzz Is printing to the same printer `HP LaserJet 400 M401 PCL6 Class Driver(副本1)` succeeded from browser print dialog?

**Comment by clayzzzzzzzzzz** [comment]
> rinting to the same

Thanks

**Comment by clayzzzzzzzzzz** [comment]
> @clayzzzzzzzzzz Is printing to the same printer `HP LaserJet 400 M401 PCL6 Class Driver(副本1)` succeeded from browser print dialog?

Yes! 
When i rename this printer  to ”HP LaserJet 400 M401 PCL6 Class Driver()“ and “HP LaserJet 400 M401 PCL6 Class Driver”，webview2(v1.0.1722.32) will always print successfully.

**Comment by monica-ch** [comment]
@clayzzzzzzzzzz Looks like issued is resolved. Closing the issue, feel free to reopen if you have any questions.

**Comment by clayzzzzzzzzzz** [comment]
> resolved. Closing the issue, feel free to reopen if you have any question

Thanks

**Comment by clayzzzzzzzzzz** [comment]
> 



> issued is resolved. Closing the issue, feel free to reopen i

Hi, this issue still exists in version 1.0.1774.30.

Version
SDK: Microsoft.Web.WebView2 v1.0.1774.30
Runtime: C# .NET Framework 4.6.1
Framework: WinForms
OS: Win10

**Comment by novac42** [comment]
Hi @monica-ch customer reports the issue still exists in version 1.0.1774.30, so I reopened the issue. May you take another look?

**Comment by monica-ch** [comment]
@clayzzzzzzzzzz Sorry you are seeing the issue again. May I know the WV2 runtime version installed on your machine?

Also, I believe printer name is either of HP LaserJet 400 M401 PCL6 Class Driver()/HP LaserJet 400 M401 PCL6 Class Driver right?

**Comment by clayzzzzzzzzzz** [comment]
> @clayzzzzzzzzzz Sorry you are seeing the issue again. May I know the WV2 runtime version installed on your machine?
> 
> Also, I believe printer name is either of HP LaserJet 400 M401 PCL6 Class Driver()/HP LaserJet 400 M401 PCL6 Class Driver right?

@monica-ch The WebView2 Runtime version is 114.0.1823.43
If the printer name is LaserJet 400 M401 PCL6 Class Driver() or HP LaserJet 400 M401 PCL6 Class Driver, it will print correctly. If the printer name contains Chinese, it will fail to print.
In addition, Some users name the printer based on its location, so there is a high possibility that printers may include Chinese characters in China.

**Comment by clayzzzzzzzzzz** [comment]
@monica-ch The WebView2 Runtime version is 114.0.1823.43
If the printer name is LaserJet 400 M401 PCL6 Class Driver() or HP LaserJet 400 M401 PCL6 Class Driver, it will print correctly. If the printer name contains Chinese, it will fail to print.
In addition, Some users name the printer based on its location, so there is a high possibility that printers may include Chinese characters in China.

**Comment by monica-ch** [comment]
@clayzzzzzzzzzz Yes able to repro it locally if printer name has Chinese characters. We are actively working on the fix and update the thread once we fix is in. Thanks!

**Comment by monica-ch** [comment]
@clayzzzzzzzzzz This should be fixed in runtimes 116.0.1932.0+. Thanks!

**Comment by clayzzzzzzzzzz** [comment]
> @clayzzzzzzzzzz This should be fixed in runtimes 116.0.1932.0+. Thanks!
Hi, @monica-ch.

I would like to know how to upgrade webview2 runtime, I upgraded webview2 from 1.0.1774.30 to 1.0.1905-prerelease in Nuget, but the runtime was still 114.0.1823.43.

**Comment by monica-ch** [comment]
@clayzzzzzzzzzz You can use Edge canary channel for testing as the fix is not in the stable runtime yet. Please refer [Testing upcoming APIs](https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/set-preview-channel) doc for more info.

**Comment by clayzzzzzzzzzz** [comment]
@monica-ch Thank you for your help
