### ISSUE TITLE
Problem with scrolling (Threaded scrolling)

### ISSUE THREAD

**Issue by AndreyTk** [MicrosoftEdge/WebView2Feedback#3576]
**Description**
From 06/06/2023, scrolling in div containers stopped working. Both in webview2 and in Edge. When I click on it, it changes the shade, but does not scroll.
If I disable the "Threaded scrolling" flag in Edge, the scrolling works fine again. How to fix this in webview2?

**Version**
Runtime: Browser WebVew2 114.0.1823.43
OS: Win10

**Regression**
Was this working before but has regressed? -  yes
If yes, what version did this last work on?  - From 06/06/2023 (I dont know version before)

**Screenshots**
![зображення](https://github.com/MicrosoftEdge/WebView2Feedback/assets/41419260/3c041bfa-709e-4502-8723-532cea468e77)

Flag in Edge, after changing which everything works again:
![зображення](https://github.com/MicrosoftEdge/WebView2Feedback/assets/41419260/d2c1a867-0557-43dd-8867-16e1b2bcd3ba)

**Comment by yannkost** [comment]
Same problem on my side. As additional information: Sometimes it works at first, but then, when moving the div with the scrolling around with javascript, it stops working. The scroll with keyboard strangely is still working. In my case, the element is also in a shadow-dom (webcomponent).

**Comment by SimonJChen** [comment]
Currently having the same issue here. I believe MSFT has a fix out for this in their beta version of edge so see if your issue persists there.

**Comment by champnic** [comment]
As this also affects the Edge browser the fix will be done there. Thanks for the report! Let me know if you don't see this fixed in prerelease Edge channels.

**Comment by champnic** [comment]
Per Edge team, sounds like this is fixed in runtimes 115+. For existing runtimes the issue can be mitigated by using these browser arguments:
`--enable-features=CompositeScrollAfterPaint,ScrollUnification`

**Comment by AndreyTk** [comment]
I have last version for WebView 114.0.1823.51. The problem is not solved and is still active. 
It is not always possible to add arguments. In my case, the launch is from SAP GUI.

**Comment by champnic** [comment]
Until the 115 runtime rolls out with the fix, you can potentially use the environment variable or registry approach for setting extra browser args outlined here:
https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environment.createasync?view=webview2-dotnet-1.0.1823.32#remarks
