### ISSUE TITLE
Crash on closing window via Alt+F4

### ISSUE THREAD

**Issue by cbra-caa** [MicrosoftEdge/WebView2Feedback#399]
### Setup
- WPF application
- .Net 4.7.2
- 0.9.579-prerelease package for WebView
- Edge Dev installed

### Problem
WebView will get a fatal error if you use Alt+F4 to close two windows in rapid succession leading to the stacktrace:

> Catching Unhandled exception:System.InvalidOperationException: Cannot change the RoutedEvent property while the RoutedEvent is being routed
>    at System.Windows.RoutedEventArgs.set_RoutedEvent(RoutedEvent value)
>    at Microsoft.Web.WebView2.Wpf.WebView2.OnPreviewKeyDown(KeyEventArgs e)
>    at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
>    at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
>    at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>    at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
>    at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
>    at System.Windows.Input.InputManager.ProcessStagingArea()
>    at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
>    at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
>    at System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
>    at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
>    at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
>    at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Code
I have created a minimum viable example which can cause the crash. Create a new WPF app with the following code:
**MainWindow.xaml**
```
<Window x:Class="TestWebView2App.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:wv2="clr-namespace:Microsoft.Web.WebView2.Wpf;assembly=Microsoft.Web.WebView2.Wpf"
        xmlns:local="clr-namespace:TestWebView2App"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
  <Grid>
    <Grid.RowDefinitions>
      <RowDefinition Height="Auto" />
      <RowDefinition Height="*" />
    </Grid.RowDefinitions>

    <Button Content="Open new window"
            Click="Button_Click" />

    <wv2:WebView2 Name="WebView"
                  Grid.Row="1"
                  Source="https://www.microsoft.com" />

  </Grid>
</Window>
```

**MainWindow.xaml.cs**
```
using System.Windows;

namespace TestWebView2App
{
  /// <summary>
  /// Interaction logic for MainWindow.xaml
  /// </summary>
  public partial class MainWindow : Window
  {
    public MainWindow()
    {
      InitializeComponent();
    }

    private void Button_Click(object sender, RoutedEventArgs e)
    {
      //Spawn new window
      new Window().Show();
    }
  }
}
```

### How to reproduce

1. Open the app
2. Drag a file into the browser (any file will do, I have tried with .config, .zip and .png)
3. A new window spawns with the content of the file, courtesy of the browser
4. Close this window with Alt+F4
5. Rapidly after this press the button in the app labeled 'Open new window'
6. Then close this window with Alt+F4
7. Crash

Step 5+6 should be performed within 3-4 seconds.
The crash appears with and without a debugger attached.

[AB#28631770](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/28631770)

**Comment by champnic** [comment]
Thanks for reporting this! I've opened a bug on our side to investigate.

**Comment by cgeier** [comment]
When running the program posted, I noticed that step #5, doesn't need to be done rapidly for the error to occur. The error seems to occur with a single key press. Pressing any one of the following keys produces the error: Alt, Ctrl, Shift, F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12, Backspace, A, B, C, ...

**Comment by nmairboeck** [comment]
I'm getting the same exception on multiple occasions. 
A consistent way to reproduce the issue is when displaying a PDF file, pressing "Save As" and closing the save dialog with the ESC or enter key. Closing the dialog with the mouse works.

**Comment by champnic** [comment]
This should be fixed in 1.0.781-prerelease. Thanks!

**Comment by jreichert73** [comment]
No. Still getting the error in Version "1.0.781-prerelease".
I also tried to reinstall the Microsoft Edge WebView2 Runtime, but that did not help either.

Regards, Jörg

**Comment by champnic** [comment]
@jreichert73 What repro steps are you using when you still see the issue? Is it the exact same set of steps and crash stack as the original post?

**Comment by jreichert73** [comment]
Yes, same repro steps as mentoined by @nmairboeck above.

**Comment by champnic** [comment]
Thanks for confirming - I've reactivated this issue and we'll take another look.

**Comment by lungareakshay** [comment]
Hi @champnic \ @jreichert73 , 

Did we got resolution for this issue?

I am also getting the same issue, when I open any html file in WebView2 - WPF application and try to "Save as" using right click context menu. If I click on save button it works fine for me. But when I hit ENTER on saveas dialog box I get the following error.


`---------------------------
Application Error - PDI
---------------------------
Cannot change the RoutedEvent property while the RoutedEvent is being routed.   at System.Windows.RoutedEventArgs.set_RoutedEvent(RoutedEvent value)

   at Microsoft.Web.WebView2.Wpf.WebView2.OnPreviewKeyUp(KeyEventArgs e)

   at System.Windows.UIElement.OnPreviewKeyUpThunk(Object sender, KeyEventArgs e)

   at System.Windows.Input.KeyEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)

   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)

   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)

   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)

   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)

   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)

   at System.Windows.Input.InputManager.ProcessStagingArea()

   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)

   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)

   at System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)

   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)

   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)

   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)

   at System.Windows.Interop.HwndSource.OnPreprocessMessageThunk(MSG& msg, Boolean& handled)

   at System.Windows.Interop.HwndSource.WeakEventPreprocessMessage.OnPreprocessMessage(MSG& msg, Boolean& handled)

   at System.Windows.Interop.ComponentDispatcherThread.RaiseThreadMessage(MSG& msg)

   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)

   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)

   at DocumentImaging.AddIn.DocImgAddIn.<>c__DisplayClass10_0.<OpenContextWindow>b__0()
---------------------------
OK   
---------------------------
`


Need help to resolve this issue. Thank you in advance!!

**Comment by lungareakshay** [comment]
Hi @cbra-caa,

Did you get resolution for this issue?

Thanks,
AkshayL

**Comment by cbra-caa** [comment]
@lungareakshay For me the 1.0.781-prerelease package solves the problem I was experiencing. But if you utilize the pdf-functionality others are still reporting it.

**Comment by cbra-caa** [comment]
We have not seen this problem in over a year - I believe it to be deprecated.
