### ISSUE TITLE
[Problem/Bug]: Partially cannot set locale used for Javascript (eg Date) and HTML (eg Input) but can for CSS (eg :lang)

### ISSUE THREAD

**Issue by tubs-coder** [MicrosoftEdge/WebView2Feedback#4204]
### What happened?

Use case:

I have an app with a Webview2, I would like content to always be rendered in a specific locale (regardless of user's location and locale) - for consistency in date formats across teams.  In this instance, I always want 'en-US'.

Problem:

Case 1:

On a PC in 'en-AU' or 'en-GB', setting "language" in CoreWebView2EnvironmentOptions to 'en-US' has no effect.  new Date().toLocaleString() and input boxes still display dd/mm/yyyy, but CSS does get the 'en-US' locale via the pseudo class "lang".

Expected behavior:
To respect the full provided locale for javascript and html too.

Case 2:

On a PC configured to any 'en' language, setting "language" to  in CoreWebView2EnvironmentOptions to 'ja-JP' DOES have an effect.  new Date().toLocaleString() and input boxes display yyyy/mm/dd correctly and CSS also gets the locale.

Expected behaviour:
Working as expected

Extra notes:

It seems that for Javascript and HTML, some kind of region negotiation is going on? which makes controlling this in your app impossible.

Workaround:

No workarounds for HTML - just avoid using most HTML input boxes and use a custom date picker component.   JS Date object can be worked around by always specifying the exact locale on object creation.

### Importance

Important. My app's user experience is significantly compromised.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

116.0.1938.76

### SDK Version

1.0.1938.49

### Framework

WPF

### Operating System

Windows 11

### OS Version

22621.2428

### Repro steps

1.  Configure your Windows Environment Language and region to 'Australia'
2. Launch a Webview2 ensuring you first set :
`var environmentOptions = new CoreWebView2EnvironmentOptions(language: "en-US");

var environment = await CoreWebView2Environment.CreateAsync(browserExecutableFolder, options: environmentOptions);
            await _webview.EnsureCoreWebView2Async(environment);`

3.  Open DevTools and type: `new  Date().toLocaleString()`, observe the date format. 

4. Load a webpage that includes `<input type="datetime-local"/>` - observe the date format.

5. Add a couple of CSS classes: `
*:lang(en-US) {
     background-color: green;
}
*:lang(en-AU) {
     background-color: red;
}
`  Open DevTools and observe the date format.

Expected Behaviour:
3.  Locale en-US -> Date format MM/DD/YYYY
4.  Locale en-US -> Date format MM/DD/YYYY
5.  *:lang(en-US) pseudo class active

Actual behaviour:
3.  Locale en-AU -> Date format DD/MM/YYYY (bad)
4.  Locale en-AU -> Date format DD/MM/YYYY (bad)
5.  *:lang(en-US) pseudo class active (good)

### Repros in Edge Browser

No

### Regression

No, this never worked

**Comment by tubs-coder** [comment]
If you require any further info then pls let me know

**Comment by dianaqu** [comment]
Hi @tubs-coder, Please update your runtime to latest version. The issue was fixed after 118

**Comment by tubs-coder** [comment]
Hi, 

Unfortunately i'm still seeing the same issue.

I've attached a simple example.  I am running Windows with Australian regional settings.  Nothing I do within code switches the locale settings inside the webview to en-US.

[WebView2DateIssue.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/14018970/WebView2DateIssue.zip)


Only changing the following setting in Windows has an effect:
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/119929626/ed18fdc1-9539-45c4-886e-f2c7edceb4f8)
Setting "language" in CoreWebView2EnvironmentOptions to "en-US" has no effect.

**Comment by dianaqu** [comment]
@tubs-coder Could you try update your SDK version as well? I think it requires both SDK and runtime update

**Comment by dianaqu** [comment]
Hi @tubs-coder,
I missed read with another. You need to use this API https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2controlleroptions2?view=webview2-1.0.2210.55#put_scriptlocale to set your script locale if you don't want it to match OS regions.

**Comment by tubs-coder** [comment]
> Hi @tubs-coder, Sorry, I missed read with another bug. You need to use this API https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2controlleroptions2?view=webview2-1.0.2210.55#put_scriptlocale to set your script locale if you don't want it to match OS regions.
> 
> add area owner to confirm @srwei

Thankyou, that's very helpful.  - I can confirm this fixes the javascript aspect (eg new Date().toLocaleDateString()).  

But unfortunately the input HTML date picker is still displaying using the OS region.  Is there a third configuration element for HTML input or is it a bug and should it change with ScriptLocale / Language?

(updated example:)
[WebView2DateIssue.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/14046444/WebView2DateIssue.zip)

**Comment by srwei** [comment]
@tubs-coder  The ScriptLocale only affects the Intl namespace object, which is why you're seeing it fixed for Date().toLocaleDateString(). Here are the docs for Intl: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl
Do you know if the input HTML date picker utilizes this object?

**Comment by tubs-coder** [comment]
> @tubs-coder The ScriptLocale only affects the Intl namespace object, which is why you're seeing it fixed for Date().toLocaleDateString(). Here are the docs for Intl: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl Do you know if the input HTML date picker utilizes this object?

Hi @srwei, Thanks that makes sense.  The standard says this should be derived from the language attribute (https://html.spec.whatwg.org/multipage/dom.html#language), however it seems Chromium uses the language of the browser (eg Opera: https://stackoverflow.com/questions/2968817/is-there-a-way-to-localize-input-type-date-in-html5).  This is why i'm hoping this should be configurable on the Webview2.

**Comment by dianaqu** [comment]
@srwei could you make sure this is not a regression or bug? If not, @tubs-coder could you file as feature request if you need it working.
