### ISSUE TITLE
[Problem/Bug]: Html page is not displayed in WebView2 123.0.2420.53

### ISSUE THREAD

**Issue by AndriiObruch** [MicrosoftEdge/WebView2Feedback#4448]
### What happened?

Html page is not displayed in WebView2 123.0.2420.53
We’ve encountered the following issue after the WebView 2 123.0.2420.53 update

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

123.0.2420.53

### Framework

Other

### Operating System

Windows 10

### OS Version

19045.4170

### Repro steps

1. Update to WebView 2 123.0.2420.53.
2. Launch the game Sherlock (https://www.microsoft.com/store/apps/9P9Z085XW4GF) or Jewels of Rome (https://www.microsoft.com/store/apps/9NGKSK2MVQW4)
3. Open the game
4. Exit the game
5. Launch it again (html page appears on the second launch)

Actual result: Html page is not displayed in WebView2 after updating to 123.0.2420.53. Please see the screenshot attached.
On 122.0.2365.92 WebView2 version html page is rendering correctly.

Expected result: The html page displays and the game starts without any issues.

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

Regression is newer Runtime

### Last working version (if regression)

122.0.2365.92

**Comment by AndriiObruch** [comment]
Download video with repro
https://github.com/MicrosoftEdge/WebView2Feedback/assets/164869196/465426bc-f82e-45ec-a9dc-6dde50254cdb

**Comment by AndriiObruch** [comment]
Also, we had repro for our Game Launcher in WebView2  123.0.2420.53

Black screen after open G5 Launcher

*WTR:*

1. Open browser
2. Open website https://www.g5.com/
3. Download the game version for Windows
4. Install the G5 Launcher
5. Open G5 Launcher

*Actual result -* black screen after open G5 Launcher.  In the previous version of WebView2 122.0.2365.92 launcher opened without problems.
*Expected result -* G5 Launcher opens
*Video with repro -*  https://github.com/MicrosoftEdge/WebView2Feedback/assets/164869196/9c3f2016-d5eb-40c8-be34-a2454d47b8df

**Comment by ringoz** [comment]
what happens here is browser crash right after successful creation (kind = COREWEBVIEW2_PROCESS_FAILED_KIND_BROWSER_PROCESS_EXITED).

after experimenting with environment options we've found the cause of such crash, it is the userDataFolder parameter for CreateCoreWebView2EnvironmentWithOptions API: it no longer works with "long" paths (with "\\?\" prefix).

there was similar issue in the past, like #1573 
but the impact of new issue is much bigger, because it results in showstopper for many many users.
it will take some time for us to deploy a workaround.

**Comment by vbryh-msft** [comment]
@ringoz @AndriiObruch  - please share the [dumps ](https://github.com/MicrosoftEdge/WebView2Feedback/blob/main/diagnostics/crash.md)if browser is crashing!

**Comment by ringoz** [comment]
well, the problem is crash dumps are located in a subfolder of the WebView2's user data folder...
which invalidness is the very reason of browser crash.
so there are no dumps available.

**Comment by vbryh-msft** [comment]
From reading the code if UDF can not be created host process should crash - not the browser. If you are getting COREWEBVIEW2_PROCESS_FAILED_KIND_BROWSER_PROCESS_EXITED it can be something else... but I may be wrong. Let us know if you will have any dumps.

**Comment by vickiez** [comment]
@ringoz thanks for reporting this! We have identified the root cause and the fix should be available in the next 123 update, tentatively scheduled for this Thursday 3/28

**Comment by joshp-redd** [comment]
We're having the exact same error with MSEdge/Webview2 except it's a white screen.
Version 123.0.2420.53 fails to open MS Edge and Webview2 just fails to open within a 3rd party application on a Windows 2016 server.
If I install 122.0.2365.92 it works without issues, so currently trying to stop auto updates to get it working again

**Comment by vbryh-msft** [comment]
123.0.2420.65 has the fix and was released yesterday.

**Comment by ringoz** [comment]
thanks, i confirm the issue is fixed

**Comment by AndriiObruch** [comment]
Thank you very much!
Issue is fixed.

**Comment by wood4099** [comment]
But ms edge 123.0.2420.65 also did not fix this issue. I downloaded the winui3 grgallery app and redirected to the weview2 function. However, a blank page appeared without displaying the demo content.


https://github.com/MicrosoftEdge/WebView2Feedback/assets/3077273/4b319a5e-14f9-4cdc-89fd-2b393ae18c2d
