### ISSUE TITLE
[Problem/Bug]: WebView2 content is unexpectedly rendered in dark mode when Windows is set in dark mode

### ISSUE THREAD

**Issue by fvanheeswijk** [MicrosoftEdge/WebView2Feedback#5392]
### What happened?

Since the 142.0.3595.11 beta version of the runtime content inside the WebView2 browser is suddenly rendered in dark mode when Windows is set to dark mode whereas this was not the case in earlier (beta) versions of the runtime.

Please revert this change as it is unexpected, we should be in control of whether we support dark mode as application developers.
Furthermore, I tested setting the [CoreWebView2Profile.PreferredColorScheme Property](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2profile.preferredcolorscheme?view=webview2-dotnet-1.0.3405.78) to *Light* and it still did not change this behavior.

### Importance

Important. My app's user experience is significantly compromised.

### Runtime Channel

Prerelease (Edge Canary/Dev/Beta)

### Runtime Version

142.0.3595.11 beta

### SDK Version

1.0.3405.78

### Framework

Winforms

### Operating System

Windows 11

### OS Version

10.0.26100

### Repro steps

Run a Windows Forms application with a WebView2 control in it with web content inside. The behavior we are seeing that the content is dark (usually), but even when that it is not the case then there is always a disruptive black flash.

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

Regression in newer Runtime

### Last working version (if regression)

141.0.3537.57 beta (most likely)

**Comment by fvanheeswijk** [comment]
Can we get any update on this?

**Comment by dhveerap** [comment]
I tried to repro the case where the theme did not change in 140, 141 and 142 and in all the versions, the behavior is same. Steps I followed
* Theme is set to Light in Windows settings
* Opened [WPF sample app](https://github.com/MicrosoftEdge/WebView2Samples/tree/main/SampleApps/WebView2WpfBrowser)
* Navigated to https://developer.microsoft.com/en-us/windows/downloads/sdk-archive/ - The page is rendered in light theme
* Change theme to dark in Windows settings
* Refresh the page https://developer.microsoft.com/en-us/windows/downloads/sdk-archive/ - The page is rendered in dark theme

Please let me know if I am missing anything.

**Comment by fvanheeswijk** [comment]
@dhveerap I notice that you are testing with WPF and not with Winforms as I indicated. However I'm not sure if that's the exact issue, I can reproduce it in 142 with the following code and cannot reproduce it in 141, thus it seems to be a regression. The key seems to be to use `NavigateToString` rather than a regular `Navigate`.

```
using System;
using System.Drawing;
using System.Windows.Forms;

using Microsoft.Web.WebView2.WinForms;

namespace WebView2DarkModeIssue
{
    static class Program
    {
        [STAThread]
        static void Main()
        {
            Environment.SetEnvironmentVariable("WEBVIEW2_RELEASE_CHANNEL_PREFERENCE", "1");

            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            Application.Run(CreateTestForm(true));
        }

        public static Form CreateTestForm(bool initial)
        {
            var form = new Form
            {
                Size = new Size(1280, 1024)
            };

            var webView2 = new WebView2
            {
                Dock = DockStyle.Fill
            };
            webView2.EnsureCoreWebView2Async();
            webView2.CoreWebView2InitializationCompleted += (sender, e) =>
            {
                webView2.CoreWebView2.NavigateToString(
@"<html>
<head>
    <title>Test</title>
</head>
<body style='color: red;'>
    When using the Dark Theme of Windows then the background will be black in runtime version 142, whereas it should be white, just as in version 141.
</html>");
            };

            form.Controls.Add(webView2);

            return form;
        }
    }
}
```

**Comment by fvanheeswijk** [comment]
It's been over a week without any answer, can we get an update on this? It degrades the user experience significantly (for dark mode users) if it gets into production.

**Comment by venky8951** [comment]
HI @fvanheeswijk Is it possible for you to try this with Canary - 143.0.3638.0

**Comment by fvanheeswijk** [comment]
@venky8951 Yes, I've just tried it with that Canary version and it still reproduces. So it hasn't been fixed yet.

**Comment by venky8951** [comment]
@fvanheeswijk  I have been trying the same code which you pasted - using navigateToString - in a sample winforms application and I'm not able to reproduce this - 

<img width="938" height="724" alt="Image" src="https://github.com/user-attachments/assets/ea492937-8d2b-424d-8203-d8d65933c8a1" />

**Comment by fvanheeswijk** [comment]
@venky8951 That is strange, I just did the same and I'm still able to reproduce it. I did notice that potentially we are setting the dark mode differently, my settings screen looks like the following.

<img width="873" height="927" alt="Image" src="https://github.com/user-attachments/assets/fa8f529d-5da6-4917-afd8-260ecca43f6f" />

Can you confirm that you have the same screen and check if you can reproduce it with this? As stated in the opening post I'm using Windows 11 Version 24H2 (OS Build 26100.6899).

**Comment by venky8951** [comment]
@fvanheeswijk I'm using the same screen as well -

<img width="878" height="751" alt="Image" src="https://github.com/user-attachments/assets/e47b7c64-bd9b-426f-a379-692c38201763" />

The fix is already in beta as well - 

I have tested in both the versions broken in 142.0.3595.33

<img width="868" height="658" alt="Image" src="https://github.com/user-attachments/assets/b4dd4d73-1088-4cfc-9976-1e868a72e33f" />

after fix in beta - 142.0.3595.41

<img width="833" height="602" alt="Image" src="https://github.com/user-attachments/assets/71a0f812-3834-4e10-93c0-df64c04e89b2" />

**Comment by venky8951** [comment]
Fix available in 142.0.3595.41

**Comment by fvanheeswijk** [comment]
@venky8951 I'm unfortunately still seeing the issue and can confirm that I also tested that with 142.0.3595.41. Can you try running the code of https://github.com/MicrosoftEdge/WebView2Feedback/issues/5392#issuecomment-3415240429 in a new project instead of the sample app? I have no address bar or 'Go!' button for example.

**Comment by fvanheeswijk** [comment]
Actually, I found another way to reproduce it! When running Microsoft Edge itself and navigating to _about:blank_ we get a white page when in dark mode, but when we do exactly the same in Microsoft Edge Beta we get a black page. That highlights exactly the same issue that I am experiencing.

In case this change in default behavior is intended then we need a way to opt out of it as it's completely unexpected when integrating the WebView2 component.

**Comment by fvanheeswijk** [comment]
@venky8951 Can you please escalate this issue? It looks version 142 will go live in the week of 6 November and having this dark mode issue that still reproduces (as mentioned two days ago) go live is not an option.

Furthermore, setting [CoreWebView2Profile.PreferredColorScheme Property](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2profile.preferredcolorscheme?view=webview2-dotnet-1.0.3537.50) to `Light` does not even seem to work, everything is still dark when in dark mode on Windows.

**Comment by Navdeep-ss** [comment]
We are working on fixing it

**Comment by niller-g** [comment]
The bug is now released in the stable version... I'm on `142.0.3595.53` and experience this issue.

**Comment by Navdeep-ss** [comment]
We have fixed the issue and you will receive the fix in stabel 2

**Comment by feldmanno** [comment]
The bug occurs in version 142.0.3595.53. Version 141.0.3537.99 still works as usual.

**Comment by icy9377** [comment]
@Navdeep-ss  We’re seeing the same bug on 142.0.3595.53. Could you tell us which version the fix will ship in

**Comment by Coke21** [comment]
The issue still persists on Edge version 142.0.3595.65 (Official build, 64-bit) with Windows set to dark mode.
A temporary workaround is to switch the Windows theme to light mode.

**Comment by JNecker** [comment]
The issue still persists. Since yesterday, many customers have been complaining that our software has become unusable because the background in our WebView suddenly appears dark, making the text unreadable.

The problem only occurs when Windows is set to dark mode.

Setting CoreWebView2Profile.PreferredColorScheme to Light has no effect — the background remains dark when Windows is in dark mode.

Edge version is 142.0.3595.65 (Official build, 64-bit)

**Comment by Navdeep-ss** [comment]
Earlier the [CoreWebView2Profile.PreferredColorScheme Property](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2profile.preferredcolorscheme?view=webview2-dotnet-1.0.3405.78) was broken, but that is fixed now on Edge version is 142.0.3595.65
now setting CoreWebView2Profile.PreferredColorScheme to light should work. I validated it myself. Make sure you are on the latest edge version to have this change

**Comment by JNecker** [comment]
Unfortunately, it doesn’t work with the CoreWebView2.Profile.PreferredColorScheme property.
We have tested it with version 142.0.3595.65.

We are calling the following code:
    await htmlContentEdit.EnsureCoreWebView2Async();
    htmlContentEdit.CoreWebView2.Profile.PreferredColorScheme = CoreWebView2PreferredColorScheme.Light;

**Comment by davidpoar** [comment]
I've tried every way I could, and the problem persists. :(

**Comment by JNecker** [comment]
> I've tried every way I could, and the problem persists. :(

It’s the same on our side :(

**Comment by albert-pragma** [comment]
Hello, the problem persists for us as well, although the version of Edge we have in Windows is 142.0.3595.65.
Our application is WinForms and uses Microsoft.Web.WebView2. I have tried updating to the latest available version of this Microsoft.Web.WebView2 nuget package (1.0.3595.46), but it still displays a black background. Could it be that we have to wait for Microsoft to release version 1.0.3595.65 of this nuget package?

**Comment by fvanheeswijk** [comment]
@Navdeep-ss Thank you for at least fixing the workaround (that only works from version 142.0.3595.65) onward. The breaking change however is still present and this still needs to be resolved. You cannot simply change existing behavior, now all of our customers will still need to update to the latest runtime version and meanwhile they cannot continue to work. This formerly beta runtime never should have gone into production. How can we prevent this from occurring in the future?

**Comment by LukasKonyushok** [comment]
Can confirm, I just installed the latest Edge update 142.0.3595.65 but my WebView2 Version stays at 142.0.3595.53 and not 142.0.3595.65, with this the problem persists

**Comment by staxel** [comment]
We got the same issue, running version 142.0.3595.65 on Windows 11 Pro

**Comment by minze-it** [comment]
I got the same issue running Edge for Business version 142.0.3595.53 (64-bit) on Windows 11 Enterprise 23H2 affecting the Telerik [.NET MAUI RichTextEditor](https://www.telerik.com/maui-ui/documentation/controls/richtexteditor/overview#-net-maui-richtexteditor-overview)

**Comment by mattmichielsen** [comment]
My workaround was to add some css to each html that I'm displaying:
body { background-color: #ffffff; color: #000000; }

**Comment by albert-pragma** [comment]
> My workaround was to add some css to each html that I'm displaying: body { background-color: #ffffff; color: #000000; }

By now, most people should have their workaround implemented. Ours also is to set a white background for the page body if the computed style of the page body we are displaying has no background color or has a transparent background.

However, the context menu and the scrollbar still appears in dark mode and does not respect the setting webView.CoreWebView2.Profile.PreferredColorScheme = CoreWebView2PreferredColorScheme.Light;

When will this be fixed?

**Comment by ajtruckle** [comment]
https://github.com/MicrosoftEdge/WebView2Feedback/issues/5441

It is a critical issue. Why on earth is this closed? IT has changed since the last NutGet release. Correct it asap. No longer able to use newer NUGet because of this.

**Comment by Navdeep-ss** [comment]
This issue is fixed in 142.0.3595.65. Make sure that when you are validating, you are checking webview2 version and not the edge stable browser version. These two are different. 
For confirming the version, you can check `C:\Program Files (x86)\Microsoft\EdgeWebView\Application` folder

**Comment by ajtruckle** [comment]
@Navdeep-ss 
Hi,
Thanks. If you see my linked ticket I verify the version numbers. The one you have stated with the fix I assume is not the latest stable. So I have no choice but downgrade to last stable for the benefit of my users.

**Comment by LukasKonyushok** [comment]
> This issue is fixed in 142.0.3595.65. Make sure that when you are validating, you are checking webview2 version and not the edge stable browser version. These two are different. For confirming the version, you can check `C:\Program Files (x86)\Microsoft\EdgeWebView\Application` folder

And in the newer Version it is broken again? I forced my Installation to  142.0.3595.69 and the problem persists

<img width="1263" height="774" alt="Image" src="https://github.com/user-attachments/assets/e6a75c8f-c3b8-4fb9-8258-2f5e836df593" />

And even with ne newest .80

<img width="912" height="851" alt="Image" src="https://github.com/user-attachments/assets/3bda5420-12bc-45c1-b695-06d0c2c4c306" />

**Comment by albert-pragma** [comment]
> This issue is fixed in 142.0.3595.65. Make sure that when you are validating, you are checking webview2 version and not the edge stable browser version. These two are different. For confirming the version, you can check `C:\Program Files (x86)\Microsoft\EdgeWebView\Application` folder

Ok, thanks, I can confirm after manually upgrading EgdeWebView to latest version the issue is solved.

**Comment by ajtruckle** [comment]
Upgrade to what version?
This is clear as mud. 🤗

Please confirm edge and wenview2 to resolve this. Thanks.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by albert-pragma** [comment]
> Upgrade to what version?
> This is clear as mud. 🤗
> 
> Please confirm edge and wenview2 to resolve this. Thanks.
> 
> Sent from Outlook for iOS<https://aka.ms/o0ukef>
> […](#)

If you update to the latest available it will work.
In my case the version is 142.0.3595.80.
https://developer.microsoft.com/en-us/Microsoft-edge/webview2/?form=MA13LH#download
I've used the "Evergreen standalone installer"

**Comment by ajtruckle** [comment]
Just tried that runtime update with the current "stable" sdk and it is not fixed:

https://github.com/user-attachments/assets/71d715db-80dd-47f2-a269-3e4d5a58b99e

As you can see, it is printing the unprintable area in dark. This is with the previous SDK:

https://github.com/user-attachments/assets/cdc5c5ac-eaee-49a5-b18f-9606e1237c08

Please advise

**Comment by ajtruckle** [comment]
<img width="3840" height="1080" alt="Image" src="https://github.com/user-attachments/assets/441ad1a0-2722-409b-a7e3-07b7d0dd4b4d" />

On the left is my app:

Runtime: 142.0.3595.80
SDK: 3537.50

And I do a Print Preview, (Save as PDF). 
On the right I use my "Preview in Microsoft Edge" feature where it displays the same data file in Edge. I trigger a print preview there.

You can clearly see the difference between the two. Edge is correct but WebView2 has that black background on the page. BTW, even if I set it to Save as PDF in the browser instance it is fine. Just Webview2.

**Comment by chris84948** [comment]
I had a similar issue in my WPF app and the fix was to just specify the preferred color scheme after initialization. Everything goes back to white.

webView.CoreWebView2.Profile.PreferredColorScheme = CoreWebView2PreferredColorScheme.Light;

**Comment by ajtruckle** [comment]
@chris84948 
I have already done that:

```cpp
	m_pWebBrowser = std::make_unique<CWebBrowser>();
	if (m_pWebBrowser != nullptr)
	{
		m_pWebBrowser->CreateAsync(
			WS_VISIBLE | WS_CHILD,
			m_rctHtmlPreview,
			this,
			1,
			[&]() {
				m_pWebBrowser->SetParent(this);
				m_pWebBrowser->EnableContextMenus(false);
				m_pWebBrowser->SetPreferredColorScheme(IsUsingDarkMode()
					? COREWEBVIEW2_PREFERRED_COLOR_SCHEME_DARK
					: COREWEBVIEW2_PREFERRED_COLOR_SCHEME_LIGHT
				);
				m_pWebBrowser->Navigate(theApp.GetCommonAppDataFolder() + L"credits.html", nullptr);
			});
	}
```

And I set the default background colour to prevent flashing:

```cpp
HRESULT CWebBrowser::OnCreateEnvironmentCompleted(
	HRESULT result,
	ICoreWebView2Environment* environment)
{
	CHECK_FAILURE(result);

	if (!environment)
		return E_FAIL;

	CHECK_FAILURE(environment->QueryInterface(IID_PPV_ARGS(&m_pImpl->m_webViewEnvironment)));
	CHECK_FAILURE(environment->QueryInterface(IID_PPV_ARGS(&m_pImpl->m_webViewEnvironment2)));

	if (DarkModeTools::InvokeUseDarkModeFunction())
	{
		auto webViewEnvironment10(m_pImpl->m_webViewEnvironment.try_query<ICoreWebView2Environment10>());
		if (webViewEnvironment10)
		{
			wil::com_ptr<ICoreWebView2ControllerOptions> options;
			webViewEnvironment10->CreateCoreWebView2ControllerOptions(&options);
			auto options3(options.try_query<ICoreWebView2ControllerOptions3>());
			if (options3)
			{
				const COREWEBVIEW2_COLOR bgColor = { 255, 
					GetRValue(DarkModeTools::kDarkBackgroundColor),
					GetGValue(DarkModeTools::kDarkBackgroundColor),
					GetBValue(DarkModeTools::kDarkBackgroundColor) }; // A, R, G, B

				options3->put_DefaultBackgroundColor(bgColor);
			}

			// Use the overload that accepts options
			CHECK_FAILURE(webViewEnvironment10->CreateCoreWebView2ControllerWithOptions(
				m_hWnd,
				options.get(),
				Callback<ICoreWebView2CreateCoreWebView2ControllerCompletedHandler>(
					this,
					&CWebBrowser::OnCreateWebViewControllerCompleted).Get()));
		}
	}
	else
	{
		// Fallback if ICoreWebView2Environment10 not available
		CHECK_FAILURE(m_pImpl->m_webViewEnvironment->CreateCoreWebView2Controller(
			m_hWnd,
			Callback<ICoreWebView2CreateCoreWebView2ControllerCompletedHandler>(
				this,
				&CWebBrowser::OnCreateWebViewControllerCompleted).Get()));
	}

	return S_OK;
}

```

This issue with backgrounds and printing to PDF never used to happen and does not happen in Edge.

**Comment by ajtruckle** [comment]
The document is the same, left is WebView2 dark mode. Right is spawned instance in Edge.

<img width="3840" height="1080" alt="Image" src="https://github.com/user-attachments/assets/fe089a16-6d2c-47b9-aaa9-bee7f9243a6c" />

**Comment by ajtruckle** [comment]
Can I confirm:

* Latest runtime
* Latest stable SDK
* Win32

If I set the "default background colour" as outlined above to dark (to prevent flashing) that is causes issues when printing to pdf etc. When I comment out the line to set the default background colour then webview2 works correctly (although it flashes when initialising).

I think that when setting the default background colour it should nnot be applied when printing. This is because the "body" element is only up to what the margins allow (when printing to pdf) and the area outside (aka the margins) is showing in that default background colour.

So I have to revert to having flickering to allow my users to have a good experience.

**Comment by ajtruckle** [comment]
I confirm it:

Setting the default background colour has the side affect of messing print to pdf. The outside area (outside margins) is rendered with the same background colour. 

Yes, Microsoft edge does not do this. So if we are to have the benefits of avoiding flashing by using default background colour, it needs to realize it should not use it when printing to PDF etc. 

Right now I have no choice but to stop setting the default background colour and allow the flashing so that printing works properly. 

This is a bug imho with the system / concept and should be addressed asap somehow. 

Thank you.

**Comment by glitch-maker** [comment]
I still encounter this bug in productions environment running on 142.0.3595.94

**Comment by ajtruckle** [comment]
Yeah. I raised a ticket and then got radio silence after a while. It is not fixed and setting default background colour is culprit. When I don’t set that then I never get a dark mode background problem with printing.

**Comment by glitch-maker** [comment]
Good to know thanks.

Nevertheless this issue necessitate to make new software hot fix build and will force the clients to update ...

**Comment by eng-marani** [comment]
I hit the same issue. After upgrading WebView2 now it flashes BLACK while initializing, irregardless of the background color specified.
This is absurd! Please make this behaviour "opt-in", because if WebView2 is a component in a complex WebForm that is white because user have choosed this theme, i want the control to retain user preferred white background, even if windows theme is dark.

Do exist any trick or workaround for using a solid white background ignoring win theme ?

**Comment by eng-marani** [comment]
Well, i see that by default the profile used by WebView2 is "Auto", but it can be changed after initialization done.
With this code below i got no more flashing:

```
//Set theme
CoreWebView2Profile profile = _webView.CoreWebView2.Profile;
if (profile != null)
{
    if (_darkMode)
        profile.PreferredColorScheme = CoreWebView2PreferredColorScheme.Dark;
    else
        profile.PreferredColorScheme = CoreWebView2PreferredColorScheme.Light;
}

```

**Comment by ajtruckle** [comment]
Yes, I use:

```
void CWebBrowser::SetPreferredColorScheme(COREWEBVIEW2_PREFERRED_COLOR_SCHEME value)
{
	wil::com_ptr<ICoreWebView2_13> webView2_13;
	webView2_13 = m_pImpl->m_webView.try_query<ICoreWebView2_13>();

	if (webView2_13)
	{
		wil::com_ptr<ICoreWebView2Profile> profile;
		CHECK_FAILURE(webView2_13->get_Profile(&profile));
		profile->put_PreferredColorScheme(value);
	}
}
```

And:

```
void CCreditsPage::InitialiseWebPreview2()
{
	if (m_pWebBrowser) return;

	m_lblHtmlPreview.GetWindowRect(m_rctHtmlPreview);
	ScreenToClient(m_rctHtmlPreview);

	m_pWebBrowser = std::make_unique<CWebBrowser>();
	if (m_pWebBrowser != nullptr)
	{
		m_pWebBrowser->CreateAsync(
			WS_VISIBLE | WS_CHILD,
			m_rctHtmlPreview,
			this,
			1,
			[&]() {
				m_pWebBrowser->SetParent(this);
				m_pWebBrowser->EnableContextMenus(false);
				m_pWebBrowser->SetPreferredColorScheme(IsUsingDarkMode()
					? COREWEBVIEW2_PREFERRED_COLOR_SCHEME_DARK
					: COREWEBVIEW2_PREFERRED_COLOR_SCHEME_LIGHT
				);
				m_pWebBrowser->Navigate(theApp.GetCommonAppDataFolder() + L"credits.html", nullptr);
			});
	}
}
```
