### ISSUE TITLE
[Problem/Bug]: window.chrome.webview is undefined

### ISSUE THREAD

**Issue by julio-guerrero-imprivata** [MicrosoftEdge/WebView2Feedback#5449]
### What happened?

The `window.chrome.webview` object is not available upon first page load, but appears after refreshing.

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

142.0.3595.80

### SDK Version

1.0.3595.46

### Framework

WPF

### Operating System

Windows 11

### Repro steps

During development, the error doesn't occur; however, if the build app is copied to a different Windows machine with a standard (not Admin) user, the problem is reproducible.

I managed to replicate the issue in a dummy app. The csproj file is using this config: `<RuntimeIdentifier>win-x64</RuntimeIdentifier>` and I copy the following build folder to reproduce the error: bin\x64\Debug\net8.0-windows\win-x64

I can share the project if you consider it's useful

### Repros in Edge Browser

Yes, issue can be reproduced in the corresponding Edge version

### Regression

Don't know

**Comment by prija-microsoft** [comment]
@julio-guerrero-imprivata can you please share traces for this as per https://aka.ms/wv2etw

**Comment by krbharadwaj** [comment]
@julio-guerrero-imprivata , could you please share the sample app you are using?

**Comment by julio-guerrero-imprivata** [comment]
Here are the files:

[WebviewNullTest.zip](https://github.com/user-attachments/files/23748700/WebviewNullTest.zip)
(It only includes the code)

@prija-microsoft After sharing the app. Do you still need the traces?

**Comment by julio-guerrero-imprivata** [comment]
Hi @prija-microsoft 
Is there any news on this?

**Comment by krbharadwaj** [comment]
Hey @julio-guerrero-imprivata , I was not able to reproduce the issue with your shared app. Though we have merged a fix recently on chrome.webview unavailability. You can try this with next dev build which is planned somewhere around 9th and let us know the results.

**Comment by julio-guerrero-imprivata** [comment]
Hi @krbharadwaj 
I did try with the latest webview2 version (1.0.3650.58) but the problem is still there. 
Please consider that to reproduce the error I copy the build folder (bin\x64\Debug\net8.0-windows\win-x64) to a virtual machine without any .Net framework.  

<img width="1446" height="688" alt="Image" src="https://github.com/user-attachments/assets/3b32c71f-2f69-47f9-8c37-5db7cdb0a05f" />

**Comment by krbharadwaj** [comment]
Fix is available in 144 beta =>144.0.3719.11.. Could you please check this issue on that runtime and let me know the results?

**Comment by krbharadwaj** [comment]
Can you please provide ETL logs, as we are not able to reproduce this issue?
you can use this script to collect the logs: https://github.com/MicrosoftEdge/WebView2Feedback/blob/main/diagnostics/script.md

**Comment by julio-guerrero-imprivata** [comment]
Hello @krbharadwaj ,
I did test the app using the Edge beta version. The `webview` object is there but for some reason the webview only shows a blank page (see attached image). Could it be related to the same issue?  
I did get the ETL logs, but it's bigger than 28Mb. So, It couldn't be attached to this comment. You can find it [here](https://limewire.com/d/uZt9b#2lLNmdyeIQ).

<img width="1537" height="662" alt="Image" src="https://github.com/user-attachments/assets/c98080c4-e6e6-49dd-af0c-0003363a88bf" />

**Comment by krbharadwaj** [comment]
@julio-guerrero-imprivata , Thank you for confirming that chrome.webview is available now. 

It seems now chrome.webview unavailability was not the cause of this blank screen. I looked at the logs and your app structure. 

Here is my analysis: 
Your app has hidden control gating. Visibility is set to Hidden initialliy and it becomes visible only later when you hit Browser.NavigationCompleted event. Although I see CoreWebView2.navigationCompleted gets fired , but I am doubting if your Browser.NavigationCompleted fired or not... Could you please confirm that? 

My hunch is frame scheduler avoids producing frames for hidden controls,, so as a quick mitigation you can try setting visibility earlier, somewhere after webview2 initialization completes and see if it fixes the issue.
Other quick checks you can try are : 
- check if windows bounds are non-zero
- default background color of window is non-white.

**Comment by julio-guerrero-imprivata** [comment]
@krbharadwaj thanks for your recommendations

Using the method: `Browser.UpdateWindowPos()` solved the blank window issue 

One final question, how long will it take for the Beta channel to reach the final released stage?
