### ISSUE TITLE
Unable to get callbacks via add_WebResourceRequested for WebView2 created via add_NewWindowRequested

### ISSUE THREAD

**Issue by pontusn** [MicrosoftEdge/WebView2Feedback#616]
We use a callbackhook via `add_WebResourceRequested` for adding request headers and serving some content from local folders.

This works perfect until we try to use windows created via `window.open`. 

Exactly the same code for hosting a second WebView2 in a separate dialog does not give any callbacks for requests when sent back via `put_NewWindow`. Other callbacks, like navigation and dev protocol, works perfect. Navigating works also, minus our headers and local content.

Attaching multiple callbacks via `add_WebResourceRequested` in our code yields similar behaviour. Our suspision is that (conflicting) callbacks are used internally.

**Version**
SDK: 1.0.622.22 (GA)
Runtime: GA
Framework: Win32
OS: Win10

**Comment by champnic** [comment]
Thanks for the report, I've added this bug to our backlog!

**Comment by yildirimcagri** [comment]
Hi, if I understood your issue correctly, I can see the WebResourceRequested events firing on a opened WebView so I cannot repro this. Are you calling AddWebResourceRequestedFilter separately and adding a separate WebResourceRequested handler on the new WebView that you created for the NewWindowRequested as well? Otherwise, it would be good to see some sample code from your side to understand the issue better.

**Comment by pontusn** [comment]
We create a new controller and WebView2 window. The new window is setup separately with filter and callbacks. The callbacks for web requests are never called.

**Comment by pontusn** [comment]
// Provide access to host API
    if (m_spExternal)
    {
        // Integrate with host
        RETURN_IF_FAILED(m_spWebViewWindow->AddHostObjectToScript(L"external", &CComVariant(m_spExternal)));

        // Inject polyfill
        std::wstring injectedScript = LoadModuleResourceAsUTF8(L"injected.js");
        if (!injectedScript.empty())
        {
            // Provide backward compatibility with IE
            RETURN_IF_FAILED(m_spWebViewWindow->AddScriptToExecuteOnDocumentCreated(injectedScript.data(), nullptr));
        }

        // Handle requests
        RETURN_IF_FAILED(m_spWebViewWindow->AddWebResourceRequestedFilter(L"http://*",
            COREWEBVIEW2_WEB_RESOURCE_CONTEXT::COREWEBVIEW2_WEB_RESOURCE_CONTEXT_ALL));
        RETURN_IF_FAILED(m_spWebViewWindow->AddWebResourceRequestedFilter(L"https://*",
            COREWEBVIEW2_WEB_RESOURCE_CONTEXT::COREWEBVIEW2_WEB_RESOURCE_CONTEXT_ALL));
        RETURN_IF_FAILED(m_spWebViewWindow->add_WebResourceRequested(Callback<ICoreWebView2WebResourceRequestedEventHandler>(
            [this](ICoreWebView2* webview, ICoreWebView2WebResourceRequestedEventArgs* args) -> HRESULT
            {
                return HandleWebResourceRequested(args);
            }
        ).Get(), nullptr));
    }

    HRESULT CWebView2Wrapper::HandleNewWindowRequested(ICoreWebView2NewWindowRequestedEventArgs* args)
    {
        CComPtr<ICoreWebView2NewWindowRequestedEventArgs> spArgs(args);

        CComPtr<ICoreWebView2Deferral> spDeferral;
        spArgs->GetDeferral(&spDeferral);

        CComPtr<IWebView2Wrapper> spControl;
        RETURN_IF_FAILED(CWebView2Wrapper::CreateInstance(&spControl));
        {
            auto pControl = static_cast<CWebView2Wrapper*>(spControl.p);
            pControl->m_spWebViewEnvironment = m_spWebViewEnvironment;
        }

        CComPtr<IWebView2Wrapper> spThis(this);
        auto pDialog = new CHtmlDialog(true, 
            [this, spThis, spArgs, spDeferral](LPDISPATCH lpDispatch)
            {
                CComPtr<ICoreWebView2> spNewWebView;
                {
                    CComQIPtr<IServiceProvider> spServiceProvider(lpDispatch);
                    if (spServiceProvider)
                    {
                        spServiceProvider->QueryService(__uuidof(ICoreWebView2), __uuidof(ICoreWebView2), (LPVOID*)&spNewWebView);
                    }
                }
                if (spNewWebView)
                {
                    spArgs->put_NewWindow(spNewWebView);
                    spArgs->put_Handled(TRUE);
                }
                spDeferral->Complete();   
            }, m_spExternal, spControl);
      
        CRect rcDialog;
        {
            CRect rcScreen;
            {
                MONITORINFO monitorInfo;
                monitorInfo.cbSize = sizeof(monitorInfo);
                auto hMonitor = ::MonitorFromWindow(m_hWnd, MONITOR_DEFAULTTONEAREST);
                ::GetMonitorInfo(hMonitor, &monitorInfo);

                rcScreen = monitorInfo.rcWork;
            }

            CComPtr<ICoreWebView2WindowFeatures> spWindowFeatures;
            args->get_WindowFeatures(&spWindowFeatures);

            BOOL hasSize = FALSE;
            if (spWindowFeatures &&
                SUCCEEDED(spWindowFeatures->HasSize(&hasSize)) &&
                hasSize)
            {
                UINT32 height = 0, width = 0;
                spWindowFeatures->get_Height(&height);
                spWindowFeatures->get_Width(&width);

                rcDialog.bottom = height;
                rcDialog.right = width;
            }
            else
            {
                rcDialog.bottom = rcScreen.Height() / 2;
                rcDialog.right = min(rcDialog.bottom, rcScreen.Width() / 2);
            }

            BOOL hasPosition = FALSE;
            if (spWindowFeatures &&
                SUCCEEDED(spWindowFeatures->HasPosition(&hasPosition)) &&
                hasPosition)
            {
                UINT32 top = 0, left = 0;
                spWindowFeatures->get_Top(&top);
                spWindowFeatures->get_Left(&left);

                rcDialog.MoveToXY(top, left);
            }
            else
            {
                rcDialog.MoveToXY(
                    rcScreen.left + (rcScreen.Width() - rcDialog.Width()) / 2,
                    rcScreen.top + (rcScreen.Height() - rcDialog.Height()) / 2);
            }
        }

        pDialog->Create(NULL);
        pDialog->SetWindowPos(NULL, &rcDialog, SWP_SHOWWINDOW | SWP_ASYNCWINDOWPOS);

        return S_OK;
    }

    HRESULT CWebView2Wrapper::HandleWebResourceRequested(ICoreWebView2WebResourceRequestedEventArgs* args)
    {
        CComPtr<ICoreWebView2WebResourceRequest> spRequest;
        RETURN_IF_FAILED(args->get_Request(&spRequest));

        wil::unique_cotaskmem_string strUri;
        RETURN_IF_FAILED(spRequest->get_Uri(&strUri));

        bool isActiveServer =
            (m_bstrServerName.Length() != 0 && _wcsnicmp(strUri.get(), m_bstrServerName, m_bstrServerName.Length()) == 0) ||
            (m_bstrServerNameAlt.Length() != 0 && _wcsnicmp(strUri.get(), m_bstrServerNameAlt, m_bstrServerNameAlt.Length()) == 0);

        CComPtr<ICoreWebView2HttpRequestHeaders> spHeaders;
        RETURN_IF_FAILED(spRequest->get_Headers(&spHeaders));

        {
            static auto headerUserAgent = L"User-Agent";

            wil::unique_cotaskmem_string userAgent;
            spHeaders->GetHeader(L"User-Agent", &userAgent);

            static thread_local CStringW strUserAgent, strDefaultUserAgent;
            if (strDefaultUserAgent != userAgent.get())
            {
                strUserAgent = strDefaultUserAgent = userAgent.get();

                // Append information about embedding module
                strUserAgent.AppendChar(_T(' '));
                strUserAgent.Append(GetModuleAndVersion(NULL));
                strUserAgent.AppendChar(_T(' '));
                strUserAgent.Append(GetModuleAndVersion(_AtlBaseModule.GetModuleInstance()));

                // Hack: Alter version number for Chrome to support simultaneous login via web client
                //  Chrome/Major.Minor.Build.Revision => Chrome/Major.Minor.Build.Random, where Revision != Random
                {
                    const auto nOffset = strUserAgent.Find(_T("Chrome/"));
                    if (nOffset != -1)
                    {
                        const auto nEnd = strUserAgent.Find(_T(' '), nOffset);

                        auto nStart = nEnd;
                        while (nStart > nOffset && strUserAgent[nStart - 1] != _T('.'))
                        {
                            --nStart;
                        }
                        const auto nCount = nEnd - nStart;

                        const auto nRevision = _ttoi(strUserAgent.Mid(nStart, nCount));

                        static thread_local int nRandom = (int)LOWORD(::GetTickCount());
                        while (nRandom == nRevision)
                        {
                            nRandom = (int)LOWORD(::GetTickCount());
                        }

                        CStringW strRandom;
                        strRandom.Format(_T("%d"), nRandom);

                        strUserAgent.Delete(nStart, nCount);
                        strUserAgent.Insert(nStart, strRandom);
                    }
                }
            }

            RETURN_IF_FAILED(spHeaders->SetHeader(L"User-Agent", strUserAgent));
        }

        // Find beginning of path: https://<server>/<path>
        LPCWSTR lpszPath = nullptr;
        {
            const auto minOffset = _countof(L"https://");
            auto urlLen = wcslen(strUri.get());
            if (urlLen > minOffset)
            {
                lpszPath = wcschr(&strUri.get()[minOffset], L'/');
            }
        }

        if (lpszPath != nullptr && wcsncmp(lpszPath, L"/_/", 3) == 0)
        {
            LPCWSTR lpszResourcePath = &lpszPath[3];
            std::wstring strHeaders;

            auto contentType = s_mimeTypes.Lookup(lpszResourcePath);
            if (!contentType.empty())
            {
                strHeaders.append(L"Content-type: ");
                strHeaders.append(contentType);
                strHeaders.append(L"\r\n");
            }

            LPCWSTR lpszType = L"BINARY";
            if (contentType == L"text/javascript")
            {
                lpszType = L"JAVASCRIPT";
            }
            else if (contentType == L"text/html")
            {
                lpszType = RT_HTML;
            }

            // Embedded resource
            CComPtr<IStream> spStream;
            {
                DWORD dwLength = 0;
                LPVOID lpData = LoadModuleResource(lpszResourcePath, &dwLength, lpszType);
                if (lpData == nullptr)
                {
                    // Also support direct reference to embedding module
                    lpData = LoadModuleResource(::GetModuleHandle(NULL), lpszResourcePath, &dwLength, lpszType);
                }
                if (lpData == nullptr)
                {
                    // Also support reference to already loaded module by name
                    auto lpszSeparator = wcschr(lpszResourcePath, _T('/'));
                    if (*lpszSeparator != _T('0'))
                    {
                        CString strModule;
                        strModule.SetString(lpszResourcePath, lpszSeparator - lpszResourcePath);
                        lpData = LoadModuleResource(::GetModuleHandle(strModule), lpszSeparator + 1, &dwLength, lpszType);
                    }
                }
                if (lpData != nullptr && dwLength != 0)
                {
                    spStream.Attach(::SHCreateMemStream((LPCBYTE)lpData, dwLength));
                }
            }

            CComPtr<ICoreWebView2WebResourceResponse> spResponse;
            if (spStream)
            {
                RETURN_IF_FAILED(m_spWebViewEnvironment->CreateWebResourceResponse(spStream, 200, L"OK", strHeaders.data(), &spResponse));
            }
            else
            {
                RETURN_IF_FAILED(m_spWebViewEnvironment->CreateWebResourceResponse(nullptr, 404, L"Not Found", nullptr, &spResponse));
            }
            RETURN_IF_FAILED(args->put_Response(spResponse));
        }
        if (isActiveServer)
        {
            if (m_bstrSessionId.Length() != 0)
            {
                RETURN_IF_FAILED(spHeaders->SetHeader(L"SessionIdentifier", m_bstrSessionId));
            }

            if (lpszPath != nullptr)
            {
                // Handle file access to WebFolder via "faked" server responses
                CComBSTR bstrLocalPath;
                RETURN_IF_FAILED(MapUrlToLocalPath(lpszPath, &bstrLocalPath));
                if (bstrLocalPath.Length() != 0)
                {
                    std::wstring strHeaders;

                    // Lookup Content-Type via file association
                    auto contentType = s_mimeTypes.Lookup(bstrLocalPath);
                    if (!contentType.empty())
                    {
                        strHeaders.append(L"Content-type: ");
                        strHeaders.append(contentType);
                        strHeaders.append(L"\r\n");
                    }

                    CComPtr<ICoreWebView2WebResourceResponse> spResponse;
                    {
                        CComPtr<IStream> spStream;
                        HRESULT hRes = ::SHCreateStreamOnFileEx(bstrLocalPath, STGM_READ, FILE_ATTRIBUTE_NORMAL, FALSE, NULL, &spStream);
                        if (SUCCEEDED(hRes))
                        {
                            RETURN_IF_FAILED(m_spWebViewEnvironment->CreateWebResourceResponse(spStream, 200, L"OK", strHeaders.data(), &spResponse));
                        }
                        else
                        {
                            switch (hRes)
                            {
                            case HRESULT_FROM_WIN32(ERROR_ACCESS_DENIED):
                                RETURN_IF_FAILED(m_spWebViewEnvironment->CreateWebResourceResponse(nullptr, 401, L"Access Denied", nullptr, &spResponse));
                                break;

                            case HRESULT_FROM_WIN32(ERROR_FILE_NOT_FOUND):
                            case HRESULT_FROM_WIN32(ERROR_PATH_NOT_FOUND):
                                RETURN_IF_FAILED(m_spWebViewEnvironment->CreateWebResourceResponse(nullptr, 404, L"Not Found", nullptr, &spResponse));
                                break;

                            case STG_E_SHAREVIOLATION:
                                RETURN_IF_FAILED(m_spWebViewEnvironment->CreateWebResourceResponse(nullptr, 403, L"Sharing Violation", nullptr, &spResponse));
                                break;

                            default:
                                RETURN_IF_FAILED(m_spWebViewEnvironment->CreateWebResourceResponse(nullptr, 500, L"Internal Error", nullptr, &spResponse));
                                break;
                            }
                        }
                    }

                    RETURN_IF_FAILED(args->put_Response(spResponse));
                }
                else if (_wcsicmp(lpszPath, L"/favicon.ico") == 0)
                {
                    // Prevent unnecessary access to server, maybe provide local ICO?
                    CComPtr<ICoreWebView2WebResourceResponse> spResponse;
                    RETURN_IF_FAILED(m_spWebViewEnvironment->CreateWebResourceResponse(nullptr, 404, L"Not found", nullptr, &spResponse));
                    RETURN_IF_FAILED(args->put_Response(spResponse));
                }
            }
        }

        return S_OK;
    }

**Comment by pontusn** [comment]
Did some more experiements and when I added this to NavigationComplete it works...

    if (--m_nDialogRetry >= 0)
    {
        // Magic? Reset filters and try again and if works...
        webview->RemoveWebResourceRequestedFilter(L"http://*",
            COREWEBVIEW2_WEB_RESOURCE_CONTEXT::COREWEBVIEW2_WEB_RESOURCE_CONTEXT_ALL);
        webview->RemoveWebResourceRequestedFilter(L"https://*",
            COREWEBVIEW2_WEB_RESOURCE_CONTEXT::COREWEBVIEW2_WEB_RESOURCE_CONTEXT_ALL);
        RETURN_IF_FAILED(webview->AddWebResourceRequestedFilter(L"http://*",
            COREWEBVIEW2_WEB_RESOURCE_CONTEXT::COREWEBVIEW2_WEB_RESOURCE_CONTEXT_ALL));
        RETURN_IF_FAILED(webview->AddWebResourceRequestedFilter(L"https://*",
            COREWEBVIEW2_WEB_RESOURCE_CONTEXT::COREWEBVIEW2_WEB_RESOURCE_CONTEXT_ALL));
        return webview->Reload();
    }

**Comment by pontusn** [comment]
Something is call order dependant. By accident I discovered that half-way in some refactoring the callback started working when I manually reloaded after initial failure.

Now I've a workaround where the callback for NavicationComplete reinstalls the filters (see example above) and then reloads. This workaround is protected by an internal counter to avoid potentially infinite loop

Maybe this information can help you pinpoint the underlying problem...

**Comment by pontusn** [comment]
Same workaround us now also used for adding host objects for `window open`.

**Comment by champnic** [comment]
This should be fixed in runtimes version 92.0.886.0+. Thanks!

**Comment by Kay-Burchardt** [comment]
> This should be fixed in runtimes version 92.0.886.0+. Thanks!

This still doesn't work. I tested it with both runtime 92.0.902.62 + SDK 1.0.902.49 and Edge Dev 93.0.961.10 + SDK 1.0.955-prerelease.

There are 3 major issues with the **first** navigation in a child window:

1) WebResourceRequested doesn't fire for GET requests. It actually fires for POST requests, though!
2) A script error "Uncaught SyntaxError: Identifier 'globalParams' has already been declared" occurs, preventing window.chrome.webview to be initialized. This is a severe issue, since it prevents access to the list of host objects.
3) The script set with AddScriptToExecuteOnDocumentCreated is not executed.

Note that all 3 issues only occur during the initial navigation and are gone in subsequent documents (either through page reload or navigations to new locations.

Our scenarios depend on working around issues 2) and 3). If you fixed them, it would make my life a lot easier. However, if you finally fix issue 1), I could at least implement an elegant workaround for issues 2) and 3) by intercepting the web request for the first navigation and providing an artificial response containing a script which reloads the page.

**Comment by mukeshmishra996** [comment]
@Kay-Burchardt  - can you please share details how you have fixed the 2nd issue. I am also facing same challenge with child window window.chrome.webview is not initialized. So, I am unable to communicate from java script to c#. Can you please help me on this
