### ISSUE TITLE
Custom Error Page - IsBuiltInErrorPageEnabled is not taking effect or causes a flash

### ISSUE THREAD

**Issue by VijayanRamachandran** [MicrosoftEdge/WebView2Feedback#634]
Currently in case of any error, WebView2 renders Web Content / Page as shown in below image.

![image](https://user-images.githubusercontent.com/25306014/99358489-9d778b80-28d3-11eb-87d8-653ffcd40671.png)

Also we have options in WebView2 to render this error page or not based on below settings.

webView.CoreWebView2.Settings.**IsBuiltInErrorPageEnabled** = true;

**Expected Functionality / API :** 

As per our requirement we need to display the error page as like the one in above image but at the same time we need to render error page of our custom application specific implementation page.

As of now there is no API / Event where we can substitute our custom application specific error page instead of default error page to WebView2.

Can you please provide an API where we can specify our Custom Error Page Information, so that whenever WebView2 decides to render error page, instead of rendering default error page it shall render custom application specific error page ?

PS: This API will help us to implement custom error page as per our application specific style and color. 

[AB#34284677](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/34284677)

**Comment by champnic** [comment]
NavigationCompleted should be able to give you information on whether the navigation succeeded or not, and then you could navigate to your local error page if navigation failed. Would that solve your scenario here?

**Comment by lamposu** [comment]
> NavigationCompleted should be able to give you information on whether the navigation succeeded or not, and then you could navigate to your local error page if navigation failed. Would that solve your scenario here?

NavigationCompleted  can get the error status is Unknown, how to get the detail of the error information?

**Comment by champnic** [comment]
We don't have extra information in the case of an unknown error. Do you have a specific error case that isn't captured in the other error statuses?

**Comment by VijayanRamachandran** [comment]
hi @champnic 

As you mentioned i tried in our end below steps.


1. webView.CoreWebView2.Settings.IsBuiltInErrorPageEnabled = false;
2. Registering for NavigationCompleted event and in NavigationCompleted event handler below code i tried.

        private void WebView_NavigationCompleted(object sender, CoreWebView2NavigationCompletedEventArgs e)
        {
            if ( ! e.IsSuccess )
            {
                webView.CoreWebView2.Navigate("<some custom error page path>");
            }
        }

It is working as expected.

Thanks....

**Comment by darbid** [comment]
@VijayanRamachandran I see the default error page flash before my custom page is shown.  Do you see that too?

**Comment by VijayanRamachandran** [comment]
@darbid 

Yes even i noticed that the default error page as you mentioned gets rendered before custom error page. 

To avoid it i tried the below settings to WebView2 instance 

             webView.CoreWebView2.Settings.**IsBuiltInErrorPageEnabled** = false;

then i am not seeing any flash or directly custom error page is rendered without rendering of default error page.

**Comment by 2Late1** [comment]
I have set webView.CoreWebView2.Settings.IsBuiltInErrorPageEnabled = false; and still the default error page flashes. Is there a way _really_ disable the built in error page?

**Comment by champnic** [comment]
@2Late1 This sounds like it might be a separate issue. Do you have steps so I can try and reproduce the issue?

**Comment by 2Late1** [comment]
@champnic The flashing for me is that built-in error page is shown quickly before I show my own custom error page even if IsBuiltInErrorPageEnabled is set to false. I have understood if I set IsBuiltInErrorPageEnabled  to false, I should get "empty page" and no error is shown by WebView2?

**Comment by nicholasdgoodman** [comment]
@2Late1  I, too, observe this behavior using WebView 1.0.902-prerelease / Runtime 91.0.864.

Setting `webView.CoreWebView2.Settings.IsBuiltInErrorPageEnabled = false;` appears to have no effect whatsoever. With a manual `.NavigateToString(...)` from the `NavigationCompleted` event, there is a noticeable flicker.

With no second navigation, the default Chromium error pages show - which is unexpected based on my understanding of the `IsBuiltInErrorPageEnabled` setting.

**Comment by champnic** [comment]
Thanks for the extra info - I've added this as a bug to our backlog.

**Comment by champnic** [comment]
This is fixed in runtimes 91.0.864.70+. Thanks!

**Comment by gokselgoktas** [comment]
This issue is still happening, exactly as @nicholasdgoodman described, in 124.0.2478.80.

**Comment by victorhuangwq** [comment]
@gokselgoktas could you create a new issue? This issue has been closed a few years ago, and what you are seeing is likely a new bug. Please provide the report with information requested in the report format (the sdk etc)
