### ISSUE TITLE
that Multiple issues when using WebView2 in VS / VS Preview - Designer not working

### ISSUE THREAD

**Issue by Zheng-Li01** [MicrosoftEdge/WebView2Feedback#895]
**Description**
An an exception dialog pops up when adding the WebView2(latest 1.0.705.50) control on Form designer of winforms core project, however the WebView2 control working well for .NET Framework project.

**Version**
SDK: 1.0.705.50
Framework :WinForms core project
OS: Win10

**Repro Steps**
1. Create a .NET Core winforms project.
2. Installed the WebView2(1.0.705.50) control from NuGet.
3. Add the WebView2 control to Form1.Design.

**Screenshots**
![ExceptionDialog](https://user-images.githubusercontent.com/38325459/106852504-04a01300-666d-11eb-90bb-db1eba369b3c.PNG)

Reproduce GIF:
![FBUpdate](https://user-images.githubusercontent.com/38325459/106852537-0e297b00-666d-11eb-9f83-dbe8b40ceac7.gif)

**Additional context**
1. The previous WebView2(1.0.664.37) version working well for winforms core project.
2. See details from here: https://developercommunity2.visualstudio.com/t/Multiple-issues-when-using-WebView2-in-V/1312120.

[AB#27485378](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/27485378)

**Comment by RussKie** [comment]
`ContextMenu` has been deprecated and removed in .NET Core 3.0: https://docs.microsoft.com/en-us/dotnet/core/compatibility/winforms#removed-controls

**Comment by champnic** [comment]
We've got a fix for this that will be available in our next prerelease SDK. Thanks!

**Comment by champnic** [comment]
This should be fixed in the latest 1.0.790-prerelease SDK package. Thanks!

**Comment by Zheng-Li01** [comment]
@champnic, verified the issue with latest 1.0.7474.44, the issue still reproduce, please see below screenshot.
 
![image](https://user-images.githubusercontent.com/38325459/112804100-93963e00-90a6-11eb-907f-23d280c481c5.png)

**Comment by champnic** [comment]
@Zheng-Li01 1.0.790-prelease is ahead of 1.0.774.44 so this is maybe expected. If you try 1.0.790-prerelease or 1.0.824-prerelease SDK package do you see this?
