### ISSUE TITLE
App Crash on WebView2 background finalize

### ISSUE THREAD

**Issue by timothymcgrath** [MicrosoftEdge/WebView2Feedback#955]
**Description**
I have a WPF app using .NET Framework 4.7.2, that contains multiple WebView2 instances. Intermittently, we get an app crash during the finalize of the WebView2 control
Here is the error from Windows Event Viewer.

Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at Microsoft.Web.WebView2.Wpf.WebView2.get_CoreWebView2()
   at Microsoft.Web.WebView2.Wpf.WebView2.Dispose(Boolean)
   at System.Windows.Interop.HwndHost.Finalize()

I can't find any way to prevent this from happening.

**Version**
WebView2 1.0.721-prerelease
.NET Framework 4.7.2

**Repro Steps**
I believe it eventually happens after a user opens a window with a WebView2 and then closes it. We dispose of the WebView2 instance, but a little while later, the app crashes (during the finalize process).

**Screenshots**

**Additional context**

[AB#31292515](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/31292515)

**Comment by jozefizso** [comment]
What thread do you dispose the WebView2 instance on?

**Comment by timothymcgrath** [comment]
It is on the UI thread when I call .Dispose(), but it seems like when the Finalize() rolls through it is on a different thread?

Here are the two places I dispose of the web control -- pardon the VB, it's an old app :) -- 
First one handles an issue with the WebView process crashing (posted in this Github project a few weeks ago):

 ```
            ' When the WebView process crashes, throw away this WebView and replace it with a new one.
            ' This is an issue that the WebView team is working on.
            ' https://github.com/MicrosoftEdge/WebView2Feedback/issues/774
            Dispatcher.BeginInvoke(Async Sub()
                                       Try
                                           If _host.Children.Count > 0 Then
                                               Try
                                                   _host.Children.Clear()
                                               Catch
                                               End Try
                                           End If

                                           ' Dispose here because if the Finalize calls Dispose, it can crash the app due to a non-UI thread call.
                                           Try
                                               _browser.Dispose()
                                           Catch
                                           End Try

```

The other one is for when a window with a browser closes:

```
                AddHandler _browser.Unloaded,
                    Sub()
                        Try
                            _browser.Dispose()
                        Catch
                        End Try
                    End Sub
```

**Comment by champnic** [comment]
Based on that stack it looks like when the finalizer is calling Dispose() from the background thread Dispose() hasn't yet been called on the WebView2. Can you put breakpoints on where you are disposing of the WebView2 and verify that it's getting called before the finalizer?

**Comment by timothymcgrath** [comment]
I checked it and I do call Dispose() from the ProcessFailedHandler, but the _browser.Dispose() throws with:
{"The group or resource is not in the correct state to perform the requested operation. (Exception from HRESULT: 0x8007139F)"}

So, I'm guessing the .Dispose() never actually happens, so the Finalizer picks it up later and then fails and it crashes my entire app. 

I can't figure out any way to prevent this app crash.

I believe this all stems from the original problem of handling the process crashes: 
https://github.com/MicrosoftEdge/WebView2Feedback/issues/774#issuecomment-768449057

**Comment by champnic** [comment]
Ya that seems related to me. We have a fix for #774 that improves this experience and I think it should fix this as well. It should make Dispose() not cause an exception when called after the browser has crashed. I'll respond to this thread when the fix is available to try in the next prerelease package.

**Comment by timothymcgrath** [comment]
Do you have a timeline on this?

If I keep a list of references to my crashed WebView2 objects that error in disposal, would that prevent the Finalizer from running and crashing the app? Until your fix goes live.

**Comment by champnic** [comment]
The next prerelease package (that will include this fix) will go out soon, within the next week or two.

That workaround sounds reasonable to try.

**Comment by champnic** [comment]
This should be fixed in the 1.0.824-prerelease SDK. Please give it a try and let us know if you run into any further issues. Thanks!

**Comment by Daveric** [comment]
It seems that the error still occurs with the current version: 1.0.2903.40
Here is the snippet from Event Viewer:

Provider: .NET Runtime
Application: MyApp.exe
Framework version: v4.0.30319
Description: The process terminated due to an unhandled exception.
Exception information: System.InvalidCastException at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(System.Object, IntPtr, IntPtr ByRef, Boolean ByRef) at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller.get_CoreWebView2() at Microsoft.Web.WebView2.Core.CoreWebView2Controller.get_CoreWebView2() at Microsoft.Web.WebView2.Wpf.WebView2Base.Uninitialize(Boolean) at Microsoft.Web.WebView2.Wpf.WebView2.Dispose(Boolean) bei System.Windows.Interop.HwndHost.Finalize()

Framework: .NET Framework 4.8, WPF
OS: Windows 11 24H2

Calling Dispose() on Unloaded works but it shouldn't be necessary, why do we need manually to Dispose this?

**Comment by rhickmott** [comment]
Looks like they closed this so it would have to be re-opened as a new bug.

**Comment by AndreyBespamyatnov** [comment]
Exception Info: System.InvalidCastException
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(System.Object, IntPtr, IntPtr ByRef, Boolean ByRef)
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller.get_CoreWebView2()
   at Microsoft.Web.WebView2.Core.CoreWebView2Controller.get_CoreWebView2()
   at Microsoft.Web.WebView2.Wpf.WebView2Base.Uninitialize(Boolean)
   at Microsoft.Web.WebView2.Wpf.WebView2.Dispose(Boolean)
   at System.Windows.Interop.HwndHost.Finalize()

we still have it sorry :(
